// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1.Error.proto

package protocol_v1;

public final class V1Error {
  private V1Error() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ErrorReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.ErrorReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     */
    boolean hasIden();
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     */
    protocol_v1.V1IdentityMsg.IdentityMsg getIden();
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     */
    protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder getIdenOrBuilder();

    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    java.util.List<protocol_v1.V1Error.Error> 
        getErrorInfoList();
    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    protocol_v1.V1Error.Error getErrorInfo(int index);
    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    int getErrorInfoCount();
    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    java.util.List<? extends protocol_v1.V1Error.ErrorOrBuilder> 
        getErrorInfoOrBuilderList();
    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    protocol_v1.V1Error.ErrorOrBuilder getErrorInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocol_v1.ErrorReq}
   */
  public  static final class ErrorReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol_v1.ErrorReq)
      ErrorReqOrBuilder {
    // Use ErrorReq.newBuilder() to construct.
    private ErrorReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ErrorReq() {
      errorInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol_v1.V1IdentityMsg.IdentityMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = iden_.toBuilder();
              }
              iden_ = input.readMessage(protocol_v1.V1IdentityMsg.IdentityMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(iden_);
                iden_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                errorInfo_ = new java.util.ArrayList<protocol_v1.V1Error.Error>();
                mutable_bitField0_ |= 0x00000002;
              }
              errorInfo_.add(input.readMessage(protocol_v1.V1Error.Error.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          errorInfo_ = java.util.Collections.unmodifiableList(errorInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_v1.V1Error.internal_static_protocol_v1_ErrorReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_v1.V1Error.internal_static_protocol_v1_ErrorReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_v1.V1Error.ErrorReq.class, protocol_v1.V1Error.ErrorReq.Builder.class);
    }

    private int bitField0_;
    public static final int IDEN_FIELD_NUMBER = 1;
    private protocol_v1.V1IdentityMsg.IdentityMsg iden_;
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     */
    public boolean hasIden() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     */
    public protocol_v1.V1IdentityMsg.IdentityMsg getIden() {
      return iden_ == null ? protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance() : iden_;
    }
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     */
    public protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder getIdenOrBuilder() {
      return iden_ == null ? protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance() : iden_;
    }

    public static final int ERRORINFO_FIELD_NUMBER = 2;
    private java.util.List<protocol_v1.V1Error.Error> errorInfo_;
    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    public java.util.List<protocol_v1.V1Error.Error> getErrorInfoList() {
      return errorInfo_;
    }
    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    public java.util.List<? extends protocol_v1.V1Error.ErrorOrBuilder> 
        getErrorInfoOrBuilderList() {
      return errorInfo_;
    }
    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    public int getErrorInfoCount() {
      return errorInfo_.size();
    }
    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    public protocol_v1.V1Error.Error getErrorInfo(int index) {
      return errorInfo_.get(index);
    }
    /**
     * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
     */
    public protocol_v1.V1Error.ErrorOrBuilder getErrorInfoOrBuilder(
        int index) {
      return errorInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIden()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getIden().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getIden());
      }
      for (int i = 0; i < errorInfo_.size(); i++) {
        output.writeMessage(2, errorInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getIden());
      }
      for (int i = 0; i < errorInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, errorInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protocol_v1.V1Error.ErrorReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Error.ErrorReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Error.ErrorReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Error.ErrorReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Error.ErrorReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Error.ErrorReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Error.ErrorReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol_v1.V1Error.ErrorReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Error.ErrorReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Error.ErrorReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol_v1.V1Error.ErrorReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.ErrorReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.ErrorReq)
        protocol_v1.V1Error.ErrorReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol_v1.V1Error.internal_static_protocol_v1_ErrorReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol_v1.V1Error.internal_static_protocol_v1_ErrorReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol_v1.V1Error.ErrorReq.class, protocol_v1.V1Error.ErrorReq.Builder.class);
      }

      // Construct using protocol_v1.V1Error.ErrorReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIdenFieldBuilder();
          getErrorInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (idenBuilder_ == null) {
          iden_ = null;
        } else {
          idenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (errorInfoBuilder_ == null) {
          errorInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          errorInfoBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol_v1.V1Error.internal_static_protocol_v1_ErrorReq_descriptor;
      }

      public protocol_v1.V1Error.ErrorReq getDefaultInstanceForType() {
        return protocol_v1.V1Error.ErrorReq.getDefaultInstance();
      }

      public protocol_v1.V1Error.ErrorReq build() {
        protocol_v1.V1Error.ErrorReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol_v1.V1Error.ErrorReq buildPartial() {
        protocol_v1.V1Error.ErrorReq result = new protocol_v1.V1Error.ErrorReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (idenBuilder_ == null) {
          result.iden_ = iden_;
        } else {
          result.iden_ = idenBuilder_.build();
        }
        if (errorInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            errorInfo_ = java.util.Collections.unmodifiableList(errorInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.errorInfo_ = errorInfo_;
        } else {
          result.errorInfo_ = errorInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol_v1.V1Error.ErrorReq) {
          return mergeFrom((protocol_v1.V1Error.ErrorReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol_v1.V1Error.ErrorReq other) {
        if (other == protocol_v1.V1Error.ErrorReq.getDefaultInstance()) return this;
        if (other.hasIden()) {
          mergeIden(other.getIden());
        }
        if (errorInfoBuilder_ == null) {
          if (!other.errorInfo_.isEmpty()) {
            if (errorInfo_.isEmpty()) {
              errorInfo_ = other.errorInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureErrorInfoIsMutable();
              errorInfo_.addAll(other.errorInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.errorInfo_.isEmpty()) {
            if (errorInfoBuilder_.isEmpty()) {
              errorInfoBuilder_.dispose();
              errorInfoBuilder_ = null;
              errorInfo_ = other.errorInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              errorInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getErrorInfoFieldBuilder() : null;
            } else {
              errorInfoBuilder_.addAllMessages(other.errorInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIden()) {
          return false;
        }
        if (!getIden().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol_v1.V1Error.ErrorReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol_v1.V1Error.ErrorReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol_v1.V1IdentityMsg.IdentityMsg iden_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          protocol_v1.V1IdentityMsg.IdentityMsg, protocol_v1.V1IdentityMsg.IdentityMsg.Builder, protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder> idenBuilder_;
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       */
      public boolean hasIden() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       */
      public protocol_v1.V1IdentityMsg.IdentityMsg getIden() {
        if (idenBuilder_ == null) {
          return iden_ == null ? protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance() : iden_;
        } else {
          return idenBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       */
      public Builder setIden(protocol_v1.V1IdentityMsg.IdentityMsg value) {
        if (idenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          iden_ = value;
          onChanged();
        } else {
          idenBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       */
      public Builder setIden(
          protocol_v1.V1IdentityMsg.IdentityMsg.Builder builderForValue) {
        if (idenBuilder_ == null) {
          iden_ = builderForValue.build();
          onChanged();
        } else {
          idenBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       */
      public Builder mergeIden(protocol_v1.V1IdentityMsg.IdentityMsg value) {
        if (idenBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              iden_ != null &&
              iden_ != protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance()) {
            iden_ =
              protocol_v1.V1IdentityMsg.IdentityMsg.newBuilder(iden_).mergeFrom(value).buildPartial();
          } else {
            iden_ = value;
          }
          onChanged();
        } else {
          idenBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       */
      public Builder clearIden() {
        if (idenBuilder_ == null) {
          iden_ = null;
          onChanged();
        } else {
          idenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       */
      public protocol_v1.V1IdentityMsg.IdentityMsg.Builder getIdenBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdenFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       */
      public protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder getIdenOrBuilder() {
        if (idenBuilder_ != null) {
          return idenBuilder_.getMessageOrBuilder();
        } else {
          return iden_ == null ?
              protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance() : iden_;
        }
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol_v1.V1IdentityMsg.IdentityMsg, protocol_v1.V1IdentityMsg.IdentityMsg.Builder, protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder> 
          getIdenFieldBuilder() {
        if (idenBuilder_ == null) {
          idenBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol_v1.V1IdentityMsg.IdentityMsg, protocol_v1.V1IdentityMsg.IdentityMsg.Builder, protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder>(
                  getIden(),
                  getParentForChildren(),
                  isClean());
          iden_ = null;
        }
        return idenBuilder_;
      }

      private java.util.List<protocol_v1.V1Error.Error> errorInfo_ =
        java.util.Collections.emptyList();
      private void ensureErrorInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          errorInfo_ = new java.util.ArrayList<protocol_v1.V1Error.Error>(errorInfo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protocol_v1.V1Error.Error, protocol_v1.V1Error.Error.Builder, protocol_v1.V1Error.ErrorOrBuilder> errorInfoBuilder_;

      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public java.util.List<protocol_v1.V1Error.Error> getErrorInfoList() {
        if (errorInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(errorInfo_);
        } else {
          return errorInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public int getErrorInfoCount() {
        if (errorInfoBuilder_ == null) {
          return errorInfo_.size();
        } else {
          return errorInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public protocol_v1.V1Error.Error getErrorInfo(int index) {
        if (errorInfoBuilder_ == null) {
          return errorInfo_.get(index);
        } else {
          return errorInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public Builder setErrorInfo(
          int index, protocol_v1.V1Error.Error value) {
        if (errorInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorInfoIsMutable();
          errorInfo_.set(index, value);
          onChanged();
        } else {
          errorInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public Builder setErrorInfo(
          int index, protocol_v1.V1Error.Error.Builder builderForValue) {
        if (errorInfoBuilder_ == null) {
          ensureErrorInfoIsMutable();
          errorInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          errorInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public Builder addErrorInfo(protocol_v1.V1Error.Error value) {
        if (errorInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorInfoIsMutable();
          errorInfo_.add(value);
          onChanged();
        } else {
          errorInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public Builder addErrorInfo(
          int index, protocol_v1.V1Error.Error value) {
        if (errorInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorInfoIsMutable();
          errorInfo_.add(index, value);
          onChanged();
        } else {
          errorInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public Builder addErrorInfo(
          protocol_v1.V1Error.Error.Builder builderForValue) {
        if (errorInfoBuilder_ == null) {
          ensureErrorInfoIsMutable();
          errorInfo_.add(builderForValue.build());
          onChanged();
        } else {
          errorInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public Builder addErrorInfo(
          int index, protocol_v1.V1Error.Error.Builder builderForValue) {
        if (errorInfoBuilder_ == null) {
          ensureErrorInfoIsMutable();
          errorInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          errorInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public Builder addAllErrorInfo(
          java.lang.Iterable<? extends protocol_v1.V1Error.Error> values) {
        if (errorInfoBuilder_ == null) {
          ensureErrorInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, errorInfo_);
          onChanged();
        } else {
          errorInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public Builder clearErrorInfo() {
        if (errorInfoBuilder_ == null) {
          errorInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          errorInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public Builder removeErrorInfo(int index) {
        if (errorInfoBuilder_ == null) {
          ensureErrorInfoIsMutable();
          errorInfo_.remove(index);
          onChanged();
        } else {
          errorInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public protocol_v1.V1Error.Error.Builder getErrorInfoBuilder(
          int index) {
        return getErrorInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public protocol_v1.V1Error.ErrorOrBuilder getErrorInfoOrBuilder(
          int index) {
        if (errorInfoBuilder_ == null) {
          return errorInfo_.get(index);  } else {
          return errorInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public java.util.List<? extends protocol_v1.V1Error.ErrorOrBuilder> 
           getErrorInfoOrBuilderList() {
        if (errorInfoBuilder_ != null) {
          return errorInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(errorInfo_);
        }
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public protocol_v1.V1Error.Error.Builder addErrorInfoBuilder() {
        return getErrorInfoFieldBuilder().addBuilder(
            protocol_v1.V1Error.Error.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public protocol_v1.V1Error.Error.Builder addErrorInfoBuilder(
          int index) {
        return getErrorInfoFieldBuilder().addBuilder(
            index, protocol_v1.V1Error.Error.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol_v1.Error ErrorInfo = 2;</code>
       */
      public java.util.List<protocol_v1.V1Error.Error.Builder> 
           getErrorInfoBuilderList() {
        return getErrorInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol_v1.V1Error.Error, protocol_v1.V1Error.Error.Builder, protocol_v1.V1Error.ErrorOrBuilder> 
          getErrorInfoFieldBuilder() {
        if (errorInfoBuilder_ == null) {
          errorInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protocol_v1.V1Error.Error, protocol_v1.V1Error.Error.Builder, protocol_v1.V1Error.ErrorOrBuilder>(
                  errorInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          errorInfo_ = null;
        }
        return errorInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protocol_v1.ErrorReq)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.ErrorReq)
    private static final protocol_v1.V1Error.ErrorReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol_v1.V1Error.ErrorReq();
    }

    public static protocol_v1.V1Error.ErrorReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ErrorReq>
        PARSER = new com.google.protobuf.AbstractParser<ErrorReq>() {
      public ErrorReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ErrorReq(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ErrorReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorReq> getParserForType() {
      return PARSER;
    }

    public protocol_v1.V1Error.ErrorReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.Error)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 Timestamp = 1 [default = 0];</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint32 Timestamp = 1 [default = 0];</code>
     */
    int getTimestamp();

    /**
     * <code>optional uint32 Type = 2 [default = 0];</code>
     *
     * <pre>
     *138 is mark downloaded setting
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional uint32 Type = 2 [default = 0];</code>
     *
     * <pre>
     *138 is mark downloaded setting
     * </pre>
     */
    int getType();

    /**
     * <code>optional uint32 Value = 3 [default = 0];</code>
     */
    boolean hasValue();
    /**
     * <code>optional uint32 Value = 3 [default = 0];</code>
     */
    int getValue();

    /**
     * <code>optional uint32 FirmwareVersion = 4 [default = 0];</code>
     */
    boolean hasFirmwareVersion();
    /**
     * <code>optional uint32 FirmwareVersion = 4 [default = 0];</code>
     */
    int getFirmwareVersion();

    /**
     * <code>optional int32 Voltage = 5 [default = 0];</code>
     */
    boolean hasVoltage();
    /**
     * <code>optional int32 Voltage = 5 [default = 0];</code>
     */
    int getVoltage();
  }
  /**
   * Protobuf type {@code protocol_v1.Error}
   */
  public  static final class Error extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol_v1.Error)
      ErrorOrBuilder {
    // Use Error.newBuilder() to construct.
    private Error(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Error() {
      timestamp_ = 0;
      type_ = 0;
      value_ = 0;
      firmwareVersion_ = 0;
      voltage_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Error(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              value_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              firmwareVersion_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              voltage_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_v1.V1Error.internal_static_protocol_v1_Error_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_v1.V1Error.internal_static_protocol_v1_Error_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_v1.V1Error.Error.class, protocol_v1.V1Error.Error.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    /**
     * <code>optional uint32 Timestamp = 1 [default = 0];</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 Timestamp = 1 [default = 0];</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional uint32 Type = 2 [default = 0];</code>
     *
     * <pre>
     *138 is mark downloaded setting
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 Type = 2 [default = 0];</code>
     *
     * <pre>
     *138 is mark downloaded setting
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private int value_;
    /**
     * <code>optional uint32 Value = 3 [default = 0];</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 Value = 3 [default = 0];</code>
     */
    public int getValue() {
      return value_;
    }

    public static final int FIRMWAREVERSION_FIELD_NUMBER = 4;
    private int firmwareVersion_;
    /**
     * <code>optional uint32 FirmwareVersion = 4 [default = 0];</code>
     */
    public boolean hasFirmwareVersion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 FirmwareVersion = 4 [default = 0];</code>
     */
    public int getFirmwareVersion() {
      return firmwareVersion_;
    }

    public static final int VOLTAGE_FIELD_NUMBER = 5;
    private int voltage_;
    /**
     * <code>optional int32 Voltage = 5 [default = 0];</code>
     */
    public boolean hasVoltage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 Voltage = 5 [default = 0];</code>
     */
    public int getVoltage() {
      return voltage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, firmwareVersion_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, voltage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, firmwareVersion_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, voltage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protocol_v1.V1Error.Error parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Error.Error parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Error.Error parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Error.Error parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Error.Error parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Error.Error parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Error.Error parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol_v1.V1Error.Error parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Error.Error parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Error.Error parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol_v1.V1Error.Error prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.Error}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.Error)
        protocol_v1.V1Error.ErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol_v1.V1Error.internal_static_protocol_v1_Error_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol_v1.V1Error.internal_static_protocol_v1_Error_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol_v1.V1Error.Error.class, protocol_v1.V1Error.Error.Builder.class);
      }

      // Construct using protocol_v1.V1Error.Error.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        firmwareVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        voltage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol_v1.V1Error.internal_static_protocol_v1_Error_descriptor;
      }

      public protocol_v1.V1Error.Error getDefaultInstanceForType() {
        return protocol_v1.V1Error.Error.getDefaultInstance();
      }

      public protocol_v1.V1Error.Error build() {
        protocol_v1.V1Error.Error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol_v1.V1Error.Error buildPartial() {
        protocol_v1.V1Error.Error result = new protocol_v1.V1Error.Error(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.firmwareVersion_ = firmwareVersion_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.voltage_ = voltage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol_v1.V1Error.Error) {
          return mergeFrom((protocol_v1.V1Error.Error)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol_v1.V1Error.Error other) {
        if (other == protocol_v1.V1Error.Error.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasFirmwareVersion()) {
          setFirmwareVersion(other.getFirmwareVersion());
        }
        if (other.hasVoltage()) {
          setVoltage(other.getVoltage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol_v1.V1Error.Error parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol_v1.V1Error.Error) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int timestamp_ ;
      /**
       * <code>optional uint32 Timestamp = 1 [default = 0];</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 Timestamp = 1 [default = 0];</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint32 Timestamp = 1 [default = 0];</code>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 Timestamp = 1 [default = 0];</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>optional uint32 Type = 2 [default = 0];</code>
       *
       * <pre>
       *138 is mark downloaded setting
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 Type = 2 [default = 0];</code>
       *
       * <pre>
       *138 is mark downloaded setting
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional uint32 Type = 2 [default = 0];</code>
       *
       * <pre>
       *138 is mark downloaded setting
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 Type = 2 [default = 0];</code>
       *
       * <pre>
       *138 is mark downloaded setting
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>optional uint32 Value = 3 [default = 0];</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 Value = 3 [default = 0];</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>optional uint32 Value = 3 [default = 0];</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 Value = 3 [default = 0];</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0;
        onChanged();
        return this;
      }

      private int firmwareVersion_ ;
      /**
       * <code>optional uint32 FirmwareVersion = 4 [default = 0];</code>
       */
      public boolean hasFirmwareVersion() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 FirmwareVersion = 4 [default = 0];</code>
       */
      public int getFirmwareVersion() {
        return firmwareVersion_;
      }
      /**
       * <code>optional uint32 FirmwareVersion = 4 [default = 0];</code>
       */
      public Builder setFirmwareVersion(int value) {
        bitField0_ |= 0x00000008;
        firmwareVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 FirmwareVersion = 4 [default = 0];</code>
       */
      public Builder clearFirmwareVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        firmwareVersion_ = 0;
        onChanged();
        return this;
      }

      private int voltage_ ;
      /**
       * <code>optional int32 Voltage = 5 [default = 0];</code>
       */
      public boolean hasVoltage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 Voltage = 5 [default = 0];</code>
       */
      public int getVoltage() {
        return voltage_;
      }
      /**
       * <code>optional int32 Voltage = 5 [default = 0];</code>
       */
      public Builder setVoltage(int value) {
        bitField0_ |= 0x00000010;
        voltage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Voltage = 5 [default = 0];</code>
       */
      public Builder clearVoltage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        voltage_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol_v1.Error)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.Error)
    private static final protocol_v1.V1Error.Error DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol_v1.V1Error.Error();
    }

    public static protocol_v1.V1Error.Error getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Error>
        PARSER = new com.google.protobuf.AbstractParser<Error>() {
      public Error parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Error(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Error> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Error> getParserForType() {
      return PARSER;
    }

    public protocol_v1.V1Error.Error getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_ErrorReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_v1_ErrorReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_Error_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_v1_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016v1.Error.proto\022\013protocol_v1\032\024v1.Identi" +
      "tyMsg.proto\"Y\n\010ErrorReq\022&\n\004Iden\030\001 \002(\0132\030." +
      "protocol_v1.IdentityMsg\022%\n\tErrorInfo\030\002 \003" +
      "(\0132\022.protocol_v1.Error\"p\n\005Error\022\024\n\tTimes" +
      "tamp\030\001 \001(\r:\0010\022\017\n\004Type\030\002 \001(\r:\0010\022\020\n\005Value\030" +
      "\003 \001(\r:\0010\022\032\n\017FirmwareVersion\030\004 \001(\r:\0010\022\022\n\007" +
      "Voltage\030\005 \001(\005:\0010B\005\242\002\002V1"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol_v1.V1IdentityMsg.getDescriptor(),
        }, assigner);
    internal_static_protocol_v1_ErrorReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_v1_ErrorReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_v1_ErrorReq_descriptor,
        new java.lang.String[] { "Iden", "ErrorInfo", });
    internal_static_protocol_v1_Error_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_v1_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_v1_Error_descriptor,
        new java.lang.String[] { "Timestamp", "Type", "Value", "FirmwareVersion", "Voltage", });
    protocol_v1.V1IdentityMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
