// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1.IdentityMsg.proto

package protocol_v1;

public final class V1IdentityMsg {
  private V1IdentityMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IdentityMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.IdentityMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 MsgToken = 3;</code>
     *
     * <pre>
     * 鉴权Token: 由DeviceID和16位随机数使用CRC16_CCITT生成, 计算初值是0xFFFF
     * </pre>
     */
    boolean hasMsgToken();
    /**
     * <code>required uint32 MsgToken = 3;</code>
     *
     * <pre>
     * 鉴权Token: 由DeviceID和16位随机数使用CRC16_CCITT生成, 计算初值是0xFFFF
     * </pre>
     */
    int getMsgToken();

    /**
     * <code>required uint32 MsgIndex = 4;</code>
     *
     * <pre>
     * 消息ID
     * </pre>
     */
    boolean hasMsgIndex();
    /**
     * <code>required uint32 MsgIndex = 4;</code>
     *
     * <pre>
     * 消息ID
     * </pre>
     */
    int getMsgIndex();

    /**
     * <code>optional string DeviceID = 5 [default = ""];</code>
     *
     * <pre>
     * 设备ID: 设备发送时必填, 服务器发送时可以不填
     * </pre>
     */
    boolean hasDeviceID();
    /**
     * <code>optional string DeviceID = 5 [default = ""];</code>
     *
     * <pre>
     * 设备ID: 设备发送时必填, 服务器发送时可以不填
     * </pre>
     */
    java.lang.String getDeviceID();
    /**
     * <code>optional string DeviceID = 5 [default = ""];</code>
     *
     * <pre>
     * 设备ID: 设备发送时必填, 服务器发送时可以不填
     * </pre>
     */
    com.google.protobuf.ByteString
        getDeviceIDBytes();

    /**
     * <code>optional int32 RspCode = 6 [default = 0];</code>
     *
     * <pre>
     * 返回结果状态: 请求包不填, 回应包必填, 0表示执行成功
     * </pre>
     */
    boolean hasRspCode();
    /**
     * <code>optional int32 RspCode = 6 [default = 0];</code>
     *
     * <pre>
     * 返回结果状态: 请求包不填, 回应包必填, 0表示执行成功
     * </pre>
     */
    int getRspCode();
  }
  /**
   * Protobuf type {@code protocol_v1.IdentityMsg}
   *
   * <pre>
   * 鉴权信息
   * </pre>
   */
  public  static final class IdentityMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol_v1.IdentityMsg)
      IdentityMsgOrBuilder {
    // Use IdentityMsg.newBuilder() to construct.
    private IdentityMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private IdentityMsg() {
      msgToken_ = 0;
      msgIndex_ = 0;
      deviceID_ = "";
      rspCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IdentityMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              msgToken_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              msgIndex_ = input.readUInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              deviceID_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              rspCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_v1.V1IdentityMsg.internal_static_protocol_v1_IdentityMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_v1.V1IdentityMsg.internal_static_protocol_v1_IdentityMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_v1.V1IdentityMsg.IdentityMsg.class, protocol_v1.V1IdentityMsg.IdentityMsg.Builder.class);
    }

    private int bitField0_;
    public static final int MSGTOKEN_FIELD_NUMBER = 3;
    private int msgToken_;
    /**
     * <code>required uint32 MsgToken = 3;</code>
     *
     * <pre>
     * 鉴权Token: 由DeviceID和16位随机数使用CRC16_CCITT生成, 计算初值是0xFFFF
     * </pre>
     */
    public boolean hasMsgToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 MsgToken = 3;</code>
     *
     * <pre>
     * 鉴权Token: 由DeviceID和16位随机数使用CRC16_CCITT生成, 计算初值是0xFFFF
     * </pre>
     */
    public int getMsgToken() {
      return msgToken_;
    }

    public static final int MSGINDEX_FIELD_NUMBER = 4;
    private int msgIndex_;
    /**
     * <code>required uint32 MsgIndex = 4;</code>
     *
     * <pre>
     * 消息ID
     * </pre>
     */
    public boolean hasMsgIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 MsgIndex = 4;</code>
     *
     * <pre>
     * 消息ID
     * </pre>
     */
    public int getMsgIndex() {
      return msgIndex_;
    }

    public static final int DEVICEID_FIELD_NUMBER = 5;
    private volatile java.lang.Object deviceID_;
    /**
     * <code>optional string DeviceID = 5 [default = ""];</code>
     *
     * <pre>
     * 设备ID: 设备发送时必填, 服务器发送时可以不填
     * </pre>
     */
    public boolean hasDeviceID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string DeviceID = 5 [default = ""];</code>
     *
     * <pre>
     * 设备ID: 设备发送时必填, 服务器发送时可以不填
     * </pre>
     */
    public java.lang.String getDeviceID() {
      java.lang.Object ref = deviceID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string DeviceID = 5 [default = ""];</code>
     *
     * <pre>
     * 设备ID: 设备发送时必填, 服务器发送时可以不填
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDeviceIDBytes() {
      java.lang.Object ref = deviceID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RSPCODE_FIELD_NUMBER = 6;
    private int rspCode_;
    /**
     * <code>optional int32 RspCode = 6 [default = 0];</code>
     *
     * <pre>
     * 返回结果状态: 请求包不填, 回应包必填, 0表示执行成功
     * </pre>
     */
    public boolean hasRspCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 RspCode = 6 [default = 0];</code>
     *
     * <pre>
     * 返回结果状态: 请求包不填, 回应包必填, 0表示执行成功
     * </pre>
     */
    public int getRspCode() {
      return rspCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(3, msgToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(4, msgIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, deviceID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(6, rspCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, msgToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, msgIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, deviceID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, rspCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1IdentityMsg.IdentityMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol_v1.V1IdentityMsg.IdentityMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.IdentityMsg}
     *
     * <pre>
     * 鉴权信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.IdentityMsg)
        protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol_v1.V1IdentityMsg.internal_static_protocol_v1_IdentityMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol_v1.V1IdentityMsg.internal_static_protocol_v1_IdentityMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol_v1.V1IdentityMsg.IdentityMsg.class, protocol_v1.V1IdentityMsg.IdentityMsg.Builder.class);
      }

      // Construct using protocol_v1.V1IdentityMsg.IdentityMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgToken_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceID_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        rspCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol_v1.V1IdentityMsg.internal_static_protocol_v1_IdentityMsg_descriptor;
      }

      public protocol_v1.V1IdentityMsg.IdentityMsg getDefaultInstanceForType() {
        return protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance();
      }

      public protocol_v1.V1IdentityMsg.IdentityMsg build() {
        protocol_v1.V1IdentityMsg.IdentityMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol_v1.V1IdentityMsg.IdentityMsg buildPartial() {
        protocol_v1.V1IdentityMsg.IdentityMsg result = new protocol_v1.V1IdentityMsg.IdentityMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgToken_ = msgToken_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgIndex_ = msgIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceID_ = deviceID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rspCode_ = rspCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol_v1.V1IdentityMsg.IdentityMsg) {
          return mergeFrom((protocol_v1.V1IdentityMsg.IdentityMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol_v1.V1IdentityMsg.IdentityMsg other) {
        if (other == protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance()) return this;
        if (other.hasMsgToken()) {
          setMsgToken(other.getMsgToken());
        }
        if (other.hasMsgIndex()) {
          setMsgIndex(other.getMsgIndex());
        }
        if (other.hasDeviceID()) {
          bitField0_ |= 0x00000004;
          deviceID_ = other.deviceID_;
          onChanged();
        }
        if (other.hasRspCode()) {
          setRspCode(other.getRspCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgToken()) {
          return false;
        }
        if (!hasMsgIndex()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol_v1.V1IdentityMsg.IdentityMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol_v1.V1IdentityMsg.IdentityMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgToken_ ;
      /**
       * <code>required uint32 MsgToken = 3;</code>
       *
       * <pre>
       * 鉴权Token: 由DeviceID和16位随机数使用CRC16_CCITT生成, 计算初值是0xFFFF
       * </pre>
       */
      public boolean hasMsgToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 MsgToken = 3;</code>
       *
       * <pre>
       * 鉴权Token: 由DeviceID和16位随机数使用CRC16_CCITT生成, 计算初值是0xFFFF
       * </pre>
       */
      public int getMsgToken() {
        return msgToken_;
      }
      /**
       * <code>required uint32 MsgToken = 3;</code>
       *
       * <pre>
       * 鉴权Token: 由DeviceID和16位随机数使用CRC16_CCITT生成, 计算初值是0xFFFF
       * </pre>
       */
      public Builder setMsgToken(int value) {
        bitField0_ |= 0x00000001;
        msgToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 MsgToken = 3;</code>
       *
       * <pre>
       * 鉴权Token: 由DeviceID和16位随机数使用CRC16_CCITT生成, 计算初值是0xFFFF
       * </pre>
       */
      public Builder clearMsgToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgToken_ = 0;
        onChanged();
        return this;
      }

      private int msgIndex_ ;
      /**
       * <code>required uint32 MsgIndex = 4;</code>
       *
       * <pre>
       * 消息ID
       * </pre>
       */
      public boolean hasMsgIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 MsgIndex = 4;</code>
       *
       * <pre>
       * 消息ID
       * </pre>
       */
      public int getMsgIndex() {
        return msgIndex_;
      }
      /**
       * <code>required uint32 MsgIndex = 4;</code>
       *
       * <pre>
       * 消息ID
       * </pre>
       */
      public Builder setMsgIndex(int value) {
        bitField0_ |= 0x00000002;
        msgIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 MsgIndex = 4;</code>
       *
       * <pre>
       * 消息ID
       * </pre>
       */
      public Builder clearMsgIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgIndex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceID_ = "";
      /**
       * <code>optional string DeviceID = 5 [default = ""];</code>
       *
       * <pre>
       * 设备ID: 设备发送时必填, 服务器发送时可以不填
       * </pre>
       */
      public boolean hasDeviceID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string DeviceID = 5 [default = ""];</code>
       *
       * <pre>
       * 设备ID: 设备发送时必填, 服务器发送时可以不填
       * </pre>
       */
      public java.lang.String getDeviceID() {
        java.lang.Object ref = deviceID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string DeviceID = 5 [default = ""];</code>
       *
       * <pre>
       * 设备ID: 设备发送时必填, 服务器发送时可以不填
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDeviceIDBytes() {
        java.lang.Object ref = deviceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string DeviceID = 5 [default = ""];</code>
       *
       * <pre>
       * 设备ID: 设备发送时必填, 服务器发送时可以不填
       * </pre>
       */
      public Builder setDeviceID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string DeviceID = 5 [default = ""];</code>
       *
       * <pre>
       * 设备ID: 设备发送时必填, 服务器发送时可以不填
       * </pre>
       */
      public Builder clearDeviceID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceID_ = getDefaultInstance().getDeviceID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string DeviceID = 5 [default = ""];</code>
       *
       * <pre>
       * 设备ID: 设备发送时必填, 服务器发送时可以不填
       * </pre>
       */
      public Builder setDeviceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceID_ = value;
        onChanged();
        return this;
      }

      private int rspCode_ ;
      /**
       * <code>optional int32 RspCode = 6 [default = 0];</code>
       *
       * <pre>
       * 返回结果状态: 请求包不填, 回应包必填, 0表示执行成功
       * </pre>
       */
      public boolean hasRspCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 RspCode = 6 [default = 0];</code>
       *
       * <pre>
       * 返回结果状态: 请求包不填, 回应包必填, 0表示执行成功
       * </pre>
       */
      public int getRspCode() {
        return rspCode_;
      }
      /**
       * <code>optional int32 RspCode = 6 [default = 0];</code>
       *
       * <pre>
       * 返回结果状态: 请求包不填, 回应包必填, 0表示执行成功
       * </pre>
       */
      public Builder setRspCode(int value) {
        bitField0_ |= 0x00000008;
        rspCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 RspCode = 6 [default = 0];</code>
       *
       * <pre>
       * 返回结果状态: 请求包不填, 回应包必填, 0表示执行成功
       * </pre>
       */
      public Builder clearRspCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rspCode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol_v1.IdentityMsg)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.IdentityMsg)
    private static final protocol_v1.V1IdentityMsg.IdentityMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol_v1.V1IdentityMsg.IdentityMsg();
    }

    public static protocol_v1.V1IdentityMsg.IdentityMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IdentityMsg>
        PARSER = new com.google.protobuf.AbstractParser<IdentityMsg>() {
      public IdentityMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new IdentityMsg(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<IdentityMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IdentityMsg> getParserForType() {
      return PARSER;
    }

    public protocol_v1.V1IdentityMsg.IdentityMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_IdentityMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_v1_IdentityMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024v1.IdentityMsg.proto\022\013protocol_v1\"Y\n\013I" +
      "dentityMsg\022\020\n\010MsgToken\030\003 \002(\r\022\020\n\010MsgIndex" +
      "\030\004 \002(\r\022\022\n\010DeviceID\030\005 \001(\t:\000\022\022\n\007RspCode\030\006 " +
      "\001(\005:\0010B\005\242\002\002V1"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_v1_IdentityMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_v1_IdentityMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_v1_IdentityMsg_descriptor,
        new java.lang.String[] { "MsgToken", "MsgIndex", "DeviceID", "RspCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
