// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1.OriginCommon.proto

package protocol_v1;

public final class V1OriginCommon {
  private V1OriginCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OriginCommonReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.OriginCommonReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>optional uint64 Timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>optional uint64 Timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     * 采样频率，每秒次数
     * </pre>
     *
     * <code>optional uint32 SamplingFreq = 2 [default = 0];</code>
     */
    boolean hasSamplingFreq();
    /**
     * <pre>
     * 采样频率，每秒次数
     * </pre>
     *
     * <code>optional uint32 SamplingFreq = 2 [default = 0];</code>
     */
    int getSamplingFreq();

    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    java.util.List<OriginCommon>
        getOriginCommonInfoList();
    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    OriginCommon getOriginCommonInfo(int index);
    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    int getOriginCommonInfoCount();
    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    java.util.List<? extends OriginCommonOrBuilder>
        getOriginCommonInfoOrBuilderList();
    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    OriginCommonOrBuilder getOriginCommonInfoOrBuilder(
        int index);

    /**
     * <pre>
     * 用于打标时传输电压
     * </pre>
     *
     * <code>optional uint32 Voltage = 4 [default = 0];</code>
     */
    boolean hasVoltage();
    /**
     * <pre>
     * 用于打标时传输电压
     * </pre>
     *
     * <code>optional uint32 Voltage = 4 [default = 0];</code>
     */
    int getVoltage();

    /**
     * <pre>
     * 打标版本：1:origin，2:origin2
     * </pre>
     *
     * <code>optional uint32 Version = 5 [default = 1];</code>
     */
    boolean hasVersion();
    /**
     * <pre>
     * 打标版本：1:origin，2:origin2
     * </pre>
     *
     * <code>optional uint32 Version = 5 [default = 1];</code>
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code protocol_v1.OriginCommonReq}
   */
  public  static final class OriginCommonReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol_v1.OriginCommonReq)
      OriginCommonReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OriginCommonReq.newBuilder() to construct.
    private OriginCommonReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OriginCommonReq() {
      originCommonInfo_ = java.util.Collections.emptyList();
      version_ = 1;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OriginCommonReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              samplingFreq_ = input.readUInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                originCommonInfo_ = new java.util.ArrayList<OriginCommon>();
                mutable_bitField0_ |= 0x00000004;
              }
              originCommonInfo_.add(
                  input.readMessage(OriginCommon.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              voltage_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              version_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          originCommonInfo_ = java.util.Collections.unmodifiableList(originCommonInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return V1OriginCommon.internal_static_protocol_v1_OriginCommonReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return V1OriginCommon.internal_static_protocol_v1_OriginCommonReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OriginCommonReq.class, Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>optional uint64 Timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>optional uint64 Timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int SAMPLINGFREQ_FIELD_NUMBER = 2;
    private int samplingFreq_;
    /**
     * <pre>
     * 采样频率，每秒次数
     * </pre>
     *
     * <code>optional uint32 SamplingFreq = 2 [default = 0];</code>
     */
    public boolean hasSamplingFreq() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 采样频率，每秒次数
     * </pre>
     *
     * <code>optional uint32 SamplingFreq = 2 [default = 0];</code>
     */
    public int getSamplingFreq() {
      return samplingFreq_;
    }

    public static final int ORIGINCOMMONINFO_FIELD_NUMBER = 3;
    private java.util.List<OriginCommon> originCommonInfo_;
    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    public java.util.List<OriginCommon> getOriginCommonInfoList() {
      return originCommonInfo_;
    }
    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    public java.util.List<? extends OriginCommonOrBuilder>
        getOriginCommonInfoOrBuilderList() {
      return originCommonInfo_;
    }
    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    public int getOriginCommonInfoCount() {
      return originCommonInfo_.size();
    }
    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    public OriginCommon getOriginCommonInfo(int index) {
      return originCommonInfo_.get(index);
    }
    /**
     * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
     */
    public OriginCommonOrBuilder getOriginCommonInfoOrBuilder(
        int index) {
      return originCommonInfo_.get(index);
    }

    public static final int VOLTAGE_FIELD_NUMBER = 4;
    private int voltage_;
    /**
     * <pre>
     * 用于打标时传输电压
     * </pre>
     *
     * <code>optional uint32 Voltage = 4 [default = 0];</code>
     */
    public boolean hasVoltage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 用于打标时传输电压
     * </pre>
     *
     * <code>optional uint32 Voltage = 4 [default = 0];</code>
     */
    public int getVoltage() {
      return voltage_;
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private int version_;
    /**
     * <pre>
     * 打标版本：1:origin，2:origin2
     * </pre>
     *
     * <code>optional uint32 Version = 5 [default = 1];</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 打标版本：1:origin，2:origin2
     * </pre>
     *
     * <code>optional uint32 Version = 5 [default = 1];</code>
     */
    public int getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, samplingFreq_);
      }
      for (int i = 0; i < originCommonInfo_.size(); i++) {
        output.writeMessage(3, originCommonInfo_.get(i));
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(4, voltage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(5, version_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, samplingFreq_);
      }
      for (int i = 0; i < originCommonInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, originCommonInfo_.get(i));
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, voltage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OriginCommonReq)) {
        return super.equals(obj);
      }
      OriginCommonReq other = (OriginCommonReq) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasSamplingFreq() != other.hasSamplingFreq()) return false;
      if (hasSamplingFreq()) {
        if (getSamplingFreq()
            != other.getSamplingFreq()) return false;
      }
      if (!getOriginCommonInfoList()
          .equals(other.getOriginCommonInfoList())) return false;
      if (hasVoltage() != other.hasVoltage()) return false;
      if (hasVoltage()) {
        if (getVoltage()
            != other.getVoltage()) return false;
      }
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasSamplingFreq()) {
        hash = (37 * hash) + SAMPLINGFREQ_FIELD_NUMBER;
        hash = (53 * hash) + getSamplingFreq();
      }
      if (getOriginCommonInfoCount() > 0) {
        hash = (37 * hash) + ORIGINCOMMONINFO_FIELD_NUMBER;
        hash = (53 * hash) + getOriginCommonInfoList().hashCode();
      }
      if (hasVoltage()) {
        hash = (37 * hash) + VOLTAGE_FIELD_NUMBER;
        hash = (53 * hash) + getVoltage();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OriginCommonReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OriginCommonReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OriginCommonReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OriginCommonReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OriginCommonReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OriginCommonReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OriginCommonReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OriginCommonReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OriginCommonReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OriginCommonReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OriginCommonReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OriginCommonReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OriginCommonReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.OriginCommonReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.OriginCommonReq)
        OriginCommonReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return V1OriginCommon.internal_static_protocol_v1_OriginCommonReq_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return V1OriginCommon.internal_static_protocol_v1_OriginCommonReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OriginCommonReq.class, Builder.class);
      }

      // Construct using protocol_v1.V1OriginCommon.OriginCommonReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOriginCommonInfoFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        samplingFreq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (originCommonInfoBuilder_ == null) {
          originCommonInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          originCommonInfoBuilder_.clear();
        }
        voltage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 1;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return V1OriginCommon.internal_static_protocol_v1_OriginCommonReq_descriptor;
      }

      @Override
      public OriginCommonReq getDefaultInstanceForType() {
        return OriginCommonReq.getDefaultInstance();
      }

      @Override
      public OriginCommonReq build() {
        OriginCommonReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public OriginCommonReq buildPartial() {
        OriginCommonReq result = new OriginCommonReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.samplingFreq_ = samplingFreq_;
          to_bitField0_ |= 0x00000002;
        }
        if (originCommonInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            originCommonInfo_ = java.util.Collections.unmodifiableList(originCommonInfo_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.originCommonInfo_ = originCommonInfo_;
        } else {
          result.originCommonInfo_ = originCommonInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.voltage_ = voltage_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OriginCommonReq) {
          return mergeFrom((OriginCommonReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OriginCommonReq other) {
        if (other == OriginCommonReq.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasSamplingFreq()) {
          setSamplingFreq(other.getSamplingFreq());
        }
        if (originCommonInfoBuilder_ == null) {
          if (!other.originCommonInfo_.isEmpty()) {
            if (originCommonInfo_.isEmpty()) {
              originCommonInfo_ = other.originCommonInfo_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureOriginCommonInfoIsMutable();
              originCommonInfo_.addAll(other.originCommonInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.originCommonInfo_.isEmpty()) {
            if (originCommonInfoBuilder_.isEmpty()) {
              originCommonInfoBuilder_.dispose();
              originCommonInfoBuilder_ = null;
              originCommonInfo_ = other.originCommonInfo_;
              bitField0_ = (bitField0_ & ~0x00000004);
              originCommonInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOriginCommonInfoFieldBuilder() : null;
            } else {
              originCommonInfoBuilder_.addAllMessages(other.originCommonInfo_);
            }
          }
        }
        if (other.hasVoltage()) {
          setVoltage(other.getVoltage());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OriginCommonReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OriginCommonReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <pre>
       * 开始时间
       * </pre>
       *
       * <code>optional uint64 Timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 开始时间
       * </pre>
       *
       * <code>optional uint64 Timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 开始时间
       * </pre>
       *
       * <code>optional uint64 Timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 开始时间
       * </pre>
       *
       * <code>optional uint64 Timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int samplingFreq_ ;
      /**
       * <pre>
       * 采样频率，每秒次数
       * </pre>
       *
       * <code>optional uint32 SamplingFreq = 2 [default = 0];</code>
       */
      public boolean hasSamplingFreq() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 采样频率，每秒次数
       * </pre>
       *
       * <code>optional uint32 SamplingFreq = 2 [default = 0];</code>
       */
      public int getSamplingFreq() {
        return samplingFreq_;
      }
      /**
       * <pre>
       * 采样频率，每秒次数
       * </pre>
       *
       * <code>optional uint32 SamplingFreq = 2 [default = 0];</code>
       */
      public Builder setSamplingFreq(int value) {
        bitField0_ |= 0x00000002;
        samplingFreq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 采样频率，每秒次数
       * </pre>
       *
       * <code>optional uint32 SamplingFreq = 2 [default = 0];</code>
       */
      public Builder clearSamplingFreq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        samplingFreq_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<OriginCommon> originCommonInfo_ =
        java.util.Collections.emptyList();
      private void ensureOriginCommonInfoIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          originCommonInfo_ = new java.util.ArrayList<OriginCommon>(originCommonInfo_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          OriginCommon, OriginCommon.Builder, OriginCommonOrBuilder> originCommonInfoBuilder_;

      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public java.util.List<OriginCommon> getOriginCommonInfoList() {
        if (originCommonInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(originCommonInfo_);
        } else {
          return originCommonInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public int getOriginCommonInfoCount() {
        if (originCommonInfoBuilder_ == null) {
          return originCommonInfo_.size();
        } else {
          return originCommonInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public OriginCommon getOriginCommonInfo(int index) {
        if (originCommonInfoBuilder_ == null) {
          return originCommonInfo_.get(index);
        } else {
          return originCommonInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public Builder setOriginCommonInfo(
          int index, OriginCommon value) {
        if (originCommonInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOriginCommonInfoIsMutable();
          originCommonInfo_.set(index, value);
          onChanged();
        } else {
          originCommonInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public Builder setOriginCommonInfo(
          int index, OriginCommon.Builder builderForValue) {
        if (originCommonInfoBuilder_ == null) {
          ensureOriginCommonInfoIsMutable();
          originCommonInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          originCommonInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public Builder addOriginCommonInfo(OriginCommon value) {
        if (originCommonInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOriginCommonInfoIsMutable();
          originCommonInfo_.add(value);
          onChanged();
        } else {
          originCommonInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public Builder addOriginCommonInfo(
          int index, OriginCommon value) {
        if (originCommonInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOriginCommonInfoIsMutable();
          originCommonInfo_.add(index, value);
          onChanged();
        } else {
          originCommonInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public Builder addOriginCommonInfo(
          OriginCommon.Builder builderForValue) {
        if (originCommonInfoBuilder_ == null) {
          ensureOriginCommonInfoIsMutable();
          originCommonInfo_.add(builderForValue.build());
          onChanged();
        } else {
          originCommonInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public Builder addOriginCommonInfo(
          int index, OriginCommon.Builder builderForValue) {
        if (originCommonInfoBuilder_ == null) {
          ensureOriginCommonInfoIsMutable();
          originCommonInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          originCommonInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public Builder addAllOriginCommonInfo(
          Iterable<? extends OriginCommon> values) {
        if (originCommonInfoBuilder_ == null) {
          ensureOriginCommonInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, originCommonInfo_);
          onChanged();
        } else {
          originCommonInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public Builder clearOriginCommonInfo() {
        if (originCommonInfoBuilder_ == null) {
          originCommonInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          originCommonInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public Builder removeOriginCommonInfo(int index) {
        if (originCommonInfoBuilder_ == null) {
          ensureOriginCommonInfoIsMutable();
          originCommonInfo_.remove(index);
          onChanged();
        } else {
          originCommonInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public OriginCommon.Builder getOriginCommonInfoBuilder(
          int index) {
        return getOriginCommonInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public OriginCommonOrBuilder getOriginCommonInfoOrBuilder(
          int index) {
        if (originCommonInfoBuilder_ == null) {
          return originCommonInfo_.get(index);  } else {
          return originCommonInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public java.util.List<? extends OriginCommonOrBuilder>
           getOriginCommonInfoOrBuilderList() {
        if (originCommonInfoBuilder_ != null) {
          return originCommonInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(originCommonInfo_);
        }
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public OriginCommon.Builder addOriginCommonInfoBuilder() {
        return getOriginCommonInfoFieldBuilder().addBuilder(
            OriginCommon.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public OriginCommon.Builder addOriginCommonInfoBuilder(
          int index) {
        return getOriginCommonInfoFieldBuilder().addBuilder(
            index, OriginCommon.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol_v1.OriginCommon OriginCommonInfo = 3;</code>
       */
      public java.util.List<OriginCommon.Builder>
           getOriginCommonInfoBuilderList() {
        return getOriginCommonInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          OriginCommon, OriginCommon.Builder, OriginCommonOrBuilder>
          getOriginCommonInfoFieldBuilder() {
        if (originCommonInfoBuilder_ == null) {
          originCommonInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              OriginCommon, OriginCommon.Builder, OriginCommonOrBuilder>(
                  originCommonInfo_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          originCommonInfo_ = null;
        }
        return originCommonInfoBuilder_;
      }

      private int voltage_ ;
      /**
       * <pre>
       * 用于打标时传输电压
       * </pre>
       *
       * <code>optional uint32 Voltage = 4 [default = 0];</code>
       */
      public boolean hasVoltage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 用于打标时传输电压
       * </pre>
       *
       * <code>optional uint32 Voltage = 4 [default = 0];</code>
       */
      public int getVoltage() {
        return voltage_;
      }
      /**
       * <pre>
       * 用于打标时传输电压
       * </pre>
       *
       * <code>optional uint32 Voltage = 4 [default = 0];</code>
       */
      public Builder setVoltage(int value) {
        bitField0_ |= 0x00000008;
        voltage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用于打标时传输电压
       * </pre>
       *
       * <code>optional uint32 Voltage = 4 [default = 0];</code>
       */
      public Builder clearVoltage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        voltage_ = 0;
        onChanged();
        return this;
      }

      private int version_ = 1;
      /**
       * <pre>
       * 打标版本：1:origin，2:origin2
       * </pre>
       *
       * <code>optional uint32 Version = 5 [default = 1];</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 打标版本：1:origin，2:origin2
       * </pre>
       *
       * <code>optional uint32 Version = 5 [default = 1];</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * 打标版本：1:origin，2:origin2
       * </pre>
       *
       * <code>optional uint32 Version = 5 [default = 1];</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000010;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 打标版本：1:origin，2:origin2
       * </pre>
       *
       * <code>optional uint32 Version = 5 [default = 1];</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000010);
        version_ = 1;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol_v1.OriginCommonReq)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.OriginCommonReq)
    private static final OriginCommonReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OriginCommonReq();
    }

    public static OriginCommonReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<OriginCommonReq>
        PARSER = new com.google.protobuf.AbstractParser<OriginCommonReq>() {
      @Override
      public OriginCommonReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OriginCommonReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OriginCommonReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OriginCommonReq> getParserForType() {
      return PARSER;
    }

    @Override
    public OriginCommonReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OriginCommonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.OriginCommon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional sint32 X = 1;</code>
     */
    boolean hasX();
    /**
     * <code>optional sint32 X = 1;</code>
     */
    int getX();

    /**
     * <code>optional sint32 Y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>optional sint32 Y = 2;</code>
     */
    int getY();

    /**
     * <code>optional sint32 Z = 3;</code>
     */
    boolean hasZ();
    /**
     * <code>optional sint32 Z = 3;</code>
     */
    int getZ();
  }
  /**
   * Protobuf type {@code protocol_v1.OriginCommon}
   */
  public  static final class OriginCommon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol_v1.OriginCommon)
      OriginCommonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OriginCommon.newBuilder() to construct.
    private OriginCommon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OriginCommon() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OriginCommon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readSInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readSInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              z_ = input.readSInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return V1OriginCommon.internal_static_protocol_v1_OriginCommon_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return V1OriginCommon.internal_static_protocol_v1_OriginCommon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OriginCommon.class, Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional sint32 X = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional sint32 X = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional sint32 Y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional sint32 Y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private int z_;
    /**
     * <code>optional sint32 Z = 3;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional sint32 Z = 3;</code>
     */
    public int getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeSInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeSInt32(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeSInt32(3, z_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, y_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, z_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OriginCommon)) {
        return super.equals(obj);
      }
      OriginCommon other = (OriginCommon) obj;

      if (hasX() != other.hasX()) return false;
      if (hasX()) {
        if (getX()
            != other.getX()) return false;
      }
      if (hasY() != other.hasY()) return false;
      if (hasY()) {
        if (getY()
            != other.getY()) return false;
      }
      if (hasZ() != other.hasZ()) return false;
      if (hasZ()) {
        if (getZ()
            != other.getZ()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getX();
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + getY();
      }
      if (hasZ()) {
        hash = (37 * hash) + Z_FIELD_NUMBER;
        hash = (53 * hash) + getZ();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OriginCommon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OriginCommon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OriginCommon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OriginCommon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OriginCommon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OriginCommon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OriginCommon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OriginCommon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OriginCommon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OriginCommon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OriginCommon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OriginCommon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OriginCommon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.OriginCommon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.OriginCommon)
        OriginCommonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return V1OriginCommon.internal_static_protocol_v1_OriginCommon_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return V1OriginCommon.internal_static_protocol_v1_OriginCommon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OriginCommon.class, Builder.class);
      }

      // Construct using protocol_v1.V1OriginCommon.OriginCommon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return V1OriginCommon.internal_static_protocol_v1_OriginCommon_descriptor;
      }

      @Override
      public OriginCommon getDefaultInstanceForType() {
        return OriginCommon.getDefaultInstance();
      }

      @Override
      public OriginCommon build() {
        OriginCommon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public OriginCommon buildPartial() {
        OriginCommon result = new OriginCommon(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.z_ = z_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OriginCommon) {
          return mergeFrom((OriginCommon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OriginCommon other) {
        if (other == OriginCommon.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OriginCommon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OriginCommon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>optional sint32 X = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional sint32 X = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional sint32 X = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 X = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional sint32 Y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional sint32 Y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional sint32 Y = 2;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 Y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      private int z_ ;
      /**
       * <code>optional sint32 Z = 3;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional sint32 Z = 3;</code>
       */
      public int getZ() {
        return z_;
      }
      /**
       * <code>optional sint32 Z = 3;</code>
       */
      public Builder setZ(int value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 Z = 3;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol_v1.OriginCommon)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.OriginCommon)
    private static final OriginCommon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OriginCommon();
    }

    public static OriginCommon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<OriginCommon>
        PARSER = new com.google.protobuf.AbstractParser<OriginCommon>() {
      @Override
      public OriginCommon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OriginCommon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OriginCommon> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OriginCommon> getParserForType() {
      return PARSER;
    }

    @Override
    public OriginCommon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_OriginCommonReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_v1_OriginCommonReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_OriginCommon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_v1_OriginCommon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025v1.OriginCommon.proto\022\013protocol_v1\"\232\001\n" +
      "\017OriginCommonReq\022\021\n\tTimestamp\030\001 \001(\004\022\027\n\014S" +
      "amplingFreq\030\002 \001(\r:\0010\0223\n\020OriginCommonInfo" +
      "\030\003 \003(\0132\031.protocol_v1.OriginCommon\022\022\n\007Vol" +
      "tage\030\004 \001(\r:\0010\022\022\n\007Version\030\005 \001(\r:\0011\"/\n\014Ori" +
      "ginCommon\022\t\n\001X\030\001 \001(\021\022\t\n\001Y\030\002 \001(\021\022\t\n\001Z\030\003 \001" +
      "(\021B\005\242\002\002V1"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_v1_OriginCommonReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_v1_OriginCommonReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_v1_OriginCommonReq_descriptor,
        new String[] { "Timestamp", "SamplingFreq", "OriginCommonInfo", "Voltage", "Version", });
    internal_static_protocol_v1_OriginCommon_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_v1_OriginCommon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_v1_OriginCommon_descriptor,
        new String[] { "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
