// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1.Shape.proto

package protocol_v1;

public final class V1Shape {
  private V1Shape() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.Point)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float Latitude = 1;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required float Latitude = 1;</code>
     */
    float getLatitude();

    /**
     * <code>required float Longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required float Longitude = 2;</code>
     */
    float getLongitude();
  }
  /**
   * Protobuf type {@code protocol_v1.Point}
   */
  public  static final class Point extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol_v1.Point)
      PointOrBuilder {
    // Use Point.newBuilder() to construct.
    private Point(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Point() {
      latitude_ = 0F;
      longitude_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Point(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_v1.V1Shape.internal_static_protocol_v1_Point_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_v1.V1Shape.internal_static_protocol_v1_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_v1.V1Shape.Point.class, protocol_v1.V1Shape.Point.Builder.class);
    }

    private int bitField0_;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private float latitude_;
    /**
     * <code>required float Latitude = 1;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float Latitude = 1;</code>
     */
    public float getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private float longitude_;
    /**
     * <code>required float Longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float Longitude = 2;</code>
     */
    public float getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, longitude_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protocol_v1.V1Shape.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Shape.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Shape.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Shape.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol_v1.V1Shape.Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Shape.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol_v1.V1Shape.Point prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.Point}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.Point)
        protocol_v1.V1Shape.PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol_v1.V1Shape.internal_static_protocol_v1_Point_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol_v1.V1Shape.internal_static_protocol_v1_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol_v1.V1Shape.Point.class, protocol_v1.V1Shape.Point.Builder.class);
      }

      // Construct using protocol_v1.V1Shape.Point.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol_v1.V1Shape.internal_static_protocol_v1_Point_descriptor;
      }

      public protocol_v1.V1Shape.Point getDefaultInstanceForType() {
        return protocol_v1.V1Shape.Point.getDefaultInstance();
      }

      public protocol_v1.V1Shape.Point build() {
        protocol_v1.V1Shape.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol_v1.V1Shape.Point buildPartial() {
        protocol_v1.V1Shape.Point result = new protocol_v1.V1Shape.Point(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol_v1.V1Shape.Point) {
          return mergeFrom((protocol_v1.V1Shape.Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol_v1.V1Shape.Point other) {
        if (other == protocol_v1.V1Shape.Point.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLatitude()) {
          return false;
        }
        if (!hasLongitude()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol_v1.V1Shape.Point parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol_v1.V1Shape.Point) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float latitude_ ;
      /**
       * <code>required float Latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float Latitude = 1;</code>
       */
      public float getLatitude() {
        return latitude_;
      }
      /**
       * <code>required float Latitude = 1;</code>
       */
      public Builder setLatitude(float value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float Latitude = 1;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0F;
        onChanged();
        return this;
      }

      private float longitude_ ;
      /**
       * <code>required float Longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float Longitude = 2;</code>
       */
      public float getLongitude() {
        return longitude_;
      }
      /**
       * <code>required float Longitude = 2;</code>
       */
      public Builder setLongitude(float value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float Longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol_v1.Point)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.Point)
    private static final protocol_v1.V1Shape.Point DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol_v1.V1Shape.Point();
    }

    public static protocol_v1.V1Shape.Point getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Point>
        PARSER = new com.google.protobuf.AbstractParser<Point>() {
      public Point parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Point(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Point> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point> getParserForType() {
      return PARSER;
    }

    public protocol_v1.V1Shape.Point getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PolygonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.Polygon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    java.util.List<protocol_v1.V1Shape.Point> 
        getPointsList();
    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    protocol_v1.V1Shape.Point getPoints(int index);
    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    int getPointsCount();
    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    java.util.List<? extends protocol_v1.V1Shape.PointOrBuilder> 
        getPointsOrBuilderList();
    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    protocol_v1.V1Shape.PointOrBuilder getPointsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocol_v1.Polygon}
   */
  public  static final class Polygon extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol_v1.Polygon)
      PolygonOrBuilder {
    // Use Polygon.newBuilder() to construct.
    private Polygon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Polygon() {
      points_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Polygon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                points_ = new java.util.ArrayList<protocol_v1.V1Shape.Point>();
                mutable_bitField0_ |= 0x00000001;
              }
              points_.add(input.readMessage(protocol_v1.V1Shape.Point.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = java.util.Collections.unmodifiableList(points_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_v1.V1Shape.internal_static_protocol_v1_Polygon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_v1.V1Shape.internal_static_protocol_v1_Polygon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_v1.V1Shape.Polygon.class, protocol_v1.V1Shape.Polygon.Builder.class);
    }

    public static final int POINTS_FIELD_NUMBER = 1;
    private java.util.List<protocol_v1.V1Shape.Point> points_;
    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    public java.util.List<protocol_v1.V1Shape.Point> getPointsList() {
      return points_;
    }
    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    public java.util.List<? extends protocol_v1.V1Shape.PointOrBuilder> 
        getPointsOrBuilderList() {
      return points_;
    }
    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    public protocol_v1.V1Shape.Point getPoints(int index) {
      return points_.get(index);
    }
    /**
     * <code>repeated .protocol_v1.Point Points = 1;</code>
     */
    public protocol_v1.V1Shape.PointOrBuilder getPointsOrBuilder(
        int index) {
      return points_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPointsCount(); i++) {
        if (!getPoints(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < points_.size(); i++) {
        output.writeMessage(1, points_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < points_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, points_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protocol_v1.V1Shape.Polygon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Shape.Polygon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Polygon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Shape.Polygon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Polygon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Shape.Polygon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Polygon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol_v1.V1Shape.Polygon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Polygon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Shape.Polygon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol_v1.V1Shape.Polygon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.Polygon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.Polygon)
        protocol_v1.V1Shape.PolygonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol_v1.V1Shape.internal_static_protocol_v1_Polygon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol_v1.V1Shape.internal_static_protocol_v1_Polygon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol_v1.V1Shape.Polygon.class, protocol_v1.V1Shape.Polygon.Builder.class);
      }

      // Construct using protocol_v1.V1Shape.Polygon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPointsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol_v1.V1Shape.internal_static_protocol_v1_Polygon_descriptor;
      }

      public protocol_v1.V1Shape.Polygon getDefaultInstanceForType() {
        return protocol_v1.V1Shape.Polygon.getDefaultInstance();
      }

      public protocol_v1.V1Shape.Polygon build() {
        protocol_v1.V1Shape.Polygon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol_v1.V1Shape.Polygon buildPartial() {
        protocol_v1.V1Shape.Polygon result = new protocol_v1.V1Shape.Polygon(this);
        int from_bitField0_ = bitField0_;
        if (pointsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            points_ = java.util.Collections.unmodifiableList(points_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.points_ = points_;
        } else {
          result.points_ = pointsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol_v1.V1Shape.Polygon) {
          return mergeFrom((protocol_v1.V1Shape.Polygon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol_v1.V1Shape.Polygon other) {
        if (other == protocol_v1.V1Shape.Polygon.getDefaultInstance()) return this;
        if (pointsBuilder_ == null) {
          if (!other.points_.isEmpty()) {
            if (points_.isEmpty()) {
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePointsIsMutable();
              points_.addAll(other.points_);
            }
            onChanged();
          }
        } else {
          if (!other.points_.isEmpty()) {
            if (pointsBuilder_.isEmpty()) {
              pointsBuilder_.dispose();
              pointsBuilder_ = null;
              points_ = other.points_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pointsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPointsFieldBuilder() : null;
            } else {
              pointsBuilder_.addAllMessages(other.points_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPointsCount(); i++) {
          if (!getPoints(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol_v1.V1Shape.Polygon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol_v1.V1Shape.Polygon) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protocol_v1.V1Shape.Point> points_ =
        java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          points_ = new java.util.ArrayList<protocol_v1.V1Shape.Point>(points_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protocol_v1.V1Shape.Point, protocol_v1.V1Shape.Point.Builder, protocol_v1.V1Shape.PointOrBuilder> pointsBuilder_;

      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public java.util.List<protocol_v1.V1Shape.Point> getPointsList() {
        if (pointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(points_);
        } else {
          return pointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public int getPointsCount() {
        if (pointsBuilder_ == null) {
          return points_.size();
        } else {
          return pointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public protocol_v1.V1Shape.Point getPoints(int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);
        } else {
          return pointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public Builder setPoints(
          int index, protocol_v1.V1Shape.Point value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.set(index, value);
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public Builder setPoints(
          int index, protocol_v1.V1Shape.Point.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public Builder addPoints(protocol_v1.V1Shape.Point value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public Builder addPoints(
          int index, protocol_v1.V1Shape.Point value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointsIsMutable();
          points_.add(index, value);
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public Builder addPoints(
          protocol_v1.V1Shape.Point.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public Builder addPoints(
          int index, protocol_v1.V1Shape.Point.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public Builder addAllPoints(
          java.lang.Iterable<? extends protocol_v1.V1Shape.Point> values) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, points_);
          onChanged();
        } else {
          pointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public Builder clearPoints() {
        if (pointsBuilder_ == null) {
          points_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public Builder removePoints(int index) {
        if (pointsBuilder_ == null) {
          ensurePointsIsMutable();
          points_.remove(index);
          onChanged();
        } else {
          pointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public protocol_v1.V1Shape.Point.Builder getPointsBuilder(
          int index) {
        return getPointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public protocol_v1.V1Shape.PointOrBuilder getPointsOrBuilder(
          int index) {
        if (pointsBuilder_ == null) {
          return points_.get(index);  } else {
          return pointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public java.util.List<? extends protocol_v1.V1Shape.PointOrBuilder> 
           getPointsOrBuilderList() {
        if (pointsBuilder_ != null) {
          return pointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(points_);
        }
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public protocol_v1.V1Shape.Point.Builder addPointsBuilder() {
        return getPointsFieldBuilder().addBuilder(
            protocol_v1.V1Shape.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public protocol_v1.V1Shape.Point.Builder addPointsBuilder(
          int index) {
        return getPointsFieldBuilder().addBuilder(
            index, protocol_v1.V1Shape.Point.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol_v1.Point Points = 1;</code>
       */
      public java.util.List<protocol_v1.V1Shape.Point.Builder> 
           getPointsBuilderList() {
        return getPointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol_v1.V1Shape.Point, protocol_v1.V1Shape.Point.Builder, protocol_v1.V1Shape.PointOrBuilder> 
          getPointsFieldBuilder() {
        if (pointsBuilder_ == null) {
          pointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protocol_v1.V1Shape.Point, protocol_v1.V1Shape.Point.Builder, protocol_v1.V1Shape.PointOrBuilder>(
                  points_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          points_ = null;
        }
        return pointsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protocol_v1.Polygon)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.Polygon)
    private static final protocol_v1.V1Shape.Polygon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol_v1.V1Shape.Polygon();
    }

    public static protocol_v1.V1Shape.Polygon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Polygon>
        PARSER = new com.google.protobuf.AbstractParser<Polygon>() {
      public Polygon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Polygon(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Polygon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Polygon> getParserForType() {
      return PARSER;
    }

    public protocol_v1.V1Shape.Polygon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CircleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.Circle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protocol_v1.Point Center = 1;</code>
     *
     * <pre>
     * 圆心 坐标
     * </pre>
     */
    boolean hasCenter();
    /**
     * <code>required .protocol_v1.Point Center = 1;</code>
     *
     * <pre>
     * 圆心 坐标
     * </pre>
     */
    protocol_v1.V1Shape.Point getCenter();
    /**
     * <code>required .protocol_v1.Point Center = 1;</code>
     *
     * <pre>
     * 圆心 坐标
     * </pre>
     */
    protocol_v1.V1Shape.PointOrBuilder getCenterOrBuilder();

    /**
     * <code>required int32 Radius = 2;</code>
     *
     * <pre>
     * 半径 米
     * </pre>
     */
    boolean hasRadius();
    /**
     * <code>required int32 Radius = 2;</code>
     *
     * <pre>
     * 半径 米
     * </pre>
     */
    int getRadius();
  }
  /**
   * Protobuf type {@code protocol_v1.Circle}
   */
  public  static final class Circle extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol_v1.Circle)
      CircleOrBuilder {
    // Use Circle.newBuilder() to construct.
    private Circle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Circle() {
      radius_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Circle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol_v1.V1Shape.Point.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = center_.toBuilder();
              }
              center_ = input.readMessage(protocol_v1.V1Shape.Point.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(center_);
                center_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              radius_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_v1.V1Shape.internal_static_protocol_v1_Circle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_v1.V1Shape.internal_static_protocol_v1_Circle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_v1.V1Shape.Circle.class, protocol_v1.V1Shape.Circle.Builder.class);
    }

    private int bitField0_;
    public static final int CENTER_FIELD_NUMBER = 1;
    private protocol_v1.V1Shape.Point center_;
    /**
     * <code>required .protocol_v1.Point Center = 1;</code>
     *
     * <pre>
     * 圆心 坐标
     * </pre>
     */
    public boolean hasCenter() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol_v1.Point Center = 1;</code>
     *
     * <pre>
     * 圆心 坐标
     * </pre>
     */
    public protocol_v1.V1Shape.Point getCenter() {
      return center_ == null ? protocol_v1.V1Shape.Point.getDefaultInstance() : center_;
    }
    /**
     * <code>required .protocol_v1.Point Center = 1;</code>
     *
     * <pre>
     * 圆心 坐标
     * </pre>
     */
    public protocol_v1.V1Shape.PointOrBuilder getCenterOrBuilder() {
      return center_ == null ? protocol_v1.V1Shape.Point.getDefaultInstance() : center_;
    }

    public static final int RADIUS_FIELD_NUMBER = 2;
    private int radius_;
    /**
     * <code>required int32 Radius = 2;</code>
     *
     * <pre>
     * 半径 米
     * </pre>
     */
    public boolean hasRadius() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 Radius = 2;</code>
     *
     * <pre>
     * 半径 米
     * </pre>
     */
    public int getRadius() {
      return radius_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCenter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRadius()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCenter().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getCenter());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, radius_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCenter());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, radius_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protocol_v1.V1Shape.Circle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Shape.Circle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Circle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Shape.Circle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Circle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Shape.Circle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Circle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol_v1.V1Shape.Circle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Shape.Circle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Shape.Circle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol_v1.V1Shape.Circle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.Circle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.Circle)
        protocol_v1.V1Shape.CircleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol_v1.V1Shape.internal_static_protocol_v1_Circle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol_v1.V1Shape.internal_static_protocol_v1_Circle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol_v1.V1Shape.Circle.class, protocol_v1.V1Shape.Circle.Builder.class);
      }

      // Construct using protocol_v1.V1Shape.Circle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCenterFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (centerBuilder_ == null) {
          center_ = null;
        } else {
          centerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        radius_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol_v1.V1Shape.internal_static_protocol_v1_Circle_descriptor;
      }

      public protocol_v1.V1Shape.Circle getDefaultInstanceForType() {
        return protocol_v1.V1Shape.Circle.getDefaultInstance();
      }

      public protocol_v1.V1Shape.Circle build() {
        protocol_v1.V1Shape.Circle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol_v1.V1Shape.Circle buildPartial() {
        protocol_v1.V1Shape.Circle result = new protocol_v1.V1Shape.Circle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (centerBuilder_ == null) {
          result.center_ = center_;
        } else {
          result.center_ = centerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.radius_ = radius_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol_v1.V1Shape.Circle) {
          return mergeFrom((protocol_v1.V1Shape.Circle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol_v1.V1Shape.Circle other) {
        if (other == protocol_v1.V1Shape.Circle.getDefaultInstance()) return this;
        if (other.hasCenter()) {
          mergeCenter(other.getCenter());
        }
        if (other.hasRadius()) {
          setRadius(other.getRadius());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCenter()) {
          return false;
        }
        if (!hasRadius()) {
          return false;
        }
        if (!getCenter().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol_v1.V1Shape.Circle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol_v1.V1Shape.Circle) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol_v1.V1Shape.Point center_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          protocol_v1.V1Shape.Point, protocol_v1.V1Shape.Point.Builder, protocol_v1.V1Shape.PointOrBuilder> centerBuilder_;
      /**
       * <code>required .protocol_v1.Point Center = 1;</code>
       *
       * <pre>
       * 圆心 坐标
       * </pre>
       */
      public boolean hasCenter() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol_v1.Point Center = 1;</code>
       *
       * <pre>
       * 圆心 坐标
       * </pre>
       */
      public protocol_v1.V1Shape.Point getCenter() {
        if (centerBuilder_ == null) {
          return center_ == null ? protocol_v1.V1Shape.Point.getDefaultInstance() : center_;
        } else {
          return centerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol_v1.Point Center = 1;</code>
       *
       * <pre>
       * 圆心 坐标
       * </pre>
       */
      public Builder setCenter(protocol_v1.V1Shape.Point value) {
        if (centerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          center_ = value;
          onChanged();
        } else {
          centerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol_v1.Point Center = 1;</code>
       *
       * <pre>
       * 圆心 坐标
       * </pre>
       */
      public Builder setCenter(
          protocol_v1.V1Shape.Point.Builder builderForValue) {
        if (centerBuilder_ == null) {
          center_ = builderForValue.build();
          onChanged();
        } else {
          centerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol_v1.Point Center = 1;</code>
       *
       * <pre>
       * 圆心 坐标
       * </pre>
       */
      public Builder mergeCenter(protocol_v1.V1Shape.Point value) {
        if (centerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              center_ != null &&
              center_ != protocol_v1.V1Shape.Point.getDefaultInstance()) {
            center_ =
              protocol_v1.V1Shape.Point.newBuilder(center_).mergeFrom(value).buildPartial();
          } else {
            center_ = value;
          }
          onChanged();
        } else {
          centerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol_v1.Point Center = 1;</code>
       *
       * <pre>
       * 圆心 坐标
       * </pre>
       */
      public Builder clearCenter() {
        if (centerBuilder_ == null) {
          center_ = null;
          onChanged();
        } else {
          centerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protocol_v1.Point Center = 1;</code>
       *
       * <pre>
       * 圆心 坐标
       * </pre>
       */
      public protocol_v1.V1Shape.Point.Builder getCenterBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCenterFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol_v1.Point Center = 1;</code>
       *
       * <pre>
       * 圆心 坐标
       * </pre>
       */
      public protocol_v1.V1Shape.PointOrBuilder getCenterOrBuilder() {
        if (centerBuilder_ != null) {
          return centerBuilder_.getMessageOrBuilder();
        } else {
          return center_ == null ?
              protocol_v1.V1Shape.Point.getDefaultInstance() : center_;
        }
      }
      /**
       * <code>required .protocol_v1.Point Center = 1;</code>
       *
       * <pre>
       * 圆心 坐标
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol_v1.V1Shape.Point, protocol_v1.V1Shape.Point.Builder, protocol_v1.V1Shape.PointOrBuilder> 
          getCenterFieldBuilder() {
        if (centerBuilder_ == null) {
          centerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol_v1.V1Shape.Point, protocol_v1.V1Shape.Point.Builder, protocol_v1.V1Shape.PointOrBuilder>(
                  getCenter(),
                  getParentForChildren(),
                  isClean());
          center_ = null;
        }
        return centerBuilder_;
      }

      private int radius_ ;
      /**
       * <code>required int32 Radius = 2;</code>
       *
       * <pre>
       * 半径 米
       * </pre>
       */
      public boolean hasRadius() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 Radius = 2;</code>
       *
       * <pre>
       * 半径 米
       * </pre>
       */
      public int getRadius() {
        return radius_;
      }
      /**
       * <code>required int32 Radius = 2;</code>
       *
       * <pre>
       * 半径 米
       * </pre>
       */
      public Builder setRadius(int value) {
        bitField0_ |= 0x00000002;
        radius_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Radius = 2;</code>
       *
       * <pre>
       * 半径 米
       * </pre>
       */
      public Builder clearRadius() {
        bitField0_ = (bitField0_ & ~0x00000002);
        radius_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol_v1.Circle)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.Circle)
    private static final protocol_v1.V1Shape.Circle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol_v1.V1Shape.Circle();
    }

    public static protocol_v1.V1Shape.Circle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Circle>
        PARSER = new com.google.protobuf.AbstractParser<Circle>() {
      public Circle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Circle(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Circle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Circle> getParserForType() {
      return PARSER;
    }

    public protocol_v1.V1Shape.Circle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_Point_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_v1_Point_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_Polygon_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_v1_Polygon_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_Circle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_v1_Circle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016v1.Shape.proto\022\013protocol_v1\",\n\005Point\022\020" +
      "\n\010Latitude\030\001 \002(\002\022\021\n\tLongitude\030\002 \002(\002\"-\n\007P" +
      "olygon\022\"\n\006Points\030\001 \003(\0132\022.protocol_v1.Poi" +
      "nt\"<\n\006Circle\022\"\n\006Center\030\001 \002(\0132\022.protocol_" +
      "v1.Point\022\016\n\006Radius\030\002 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_v1_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_v1_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_v1_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_protocol_v1_Polygon_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_v1_Polygon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_v1_Polygon_descriptor,
        new java.lang.String[] { "Points", });
    internal_static_protocol_v1_Circle_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_v1_Circle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_v1_Circle_descriptor,
        new java.lang.String[] { "Center", "Radius", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
