// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1.Structured.proto

package protocol_v1;

public final class V1Structured {
  private V1Structured() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StructuredOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.Structured)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 Timestamp = 1 [default = 0];</code>
     *
     * <pre>
     * 采集时间, unix时间戳
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint32 Timestamp = 1 [default = 0];</code>
     *
     * <pre>
     * 采集时间, unix时间戳
     * </pre>
     */
    int getTimestamp();

    /**
     * <code>optional int32 Type = 2 [default = 0];</code>
     *
     * <pre>
     * 类型, 1:于辉算法  11:以色列4s odba
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional int32 Type = 2 [default = 0];</code>
     *
     * <pre>
     * 类型, 1:于辉算法  11:以色列4s odba
     * </pre>
     */
    int getType();

    /**
     * <code>optional bytes Data = 3 [default = ""];</code>
     *
     * <pre>
     * 数据, data[0:2]是数据长度
     * </pre>
     */
    boolean hasData();
    /**
     * <code>optional bytes Data = 3 [default = ""];</code>
     *
     * <pre>
     * 数据, data[0:2]是数据长度
     * </pre>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code protocol_v1.Structured}
   */
  public  static final class Structured extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol_v1.Structured)
      StructuredOrBuilder {
    // Use Structured.newBuilder() to construct.
    private Structured(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Structured() {
      timestamp_ = 0;
      type_ = 0;
      data_ = com.google.protobuf.Internal.bytesDefaultValue("");
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Structured(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_v1.V1Structured.internal_static_protocol_v1_Structured_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_v1.V1Structured.internal_static_protocol_v1_Structured_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_v1.V1Structured.Structured.class, protocol_v1.V1Structured.Structured.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    /**
     * <code>optional uint32 Timestamp = 1 [default = 0];</code>
     *
     * <pre>
     * 采集时间, unix时间戳
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 Timestamp = 1 [default = 0];</code>
     *
     * <pre>
     * 采集时间, unix时间戳
     * </pre>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional int32 Type = 2 [default = 0];</code>
     *
     * <pre>
     * 类型, 1:于辉算法  11:以色列4s odba
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 Type = 2 [default = 0];</code>
     *
     * <pre>
     * 类型, 1:于辉算法  11:以色列4s odba
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes Data = 3 [default = ""];</code>
     *
     * <pre>
     * 数据, data[0:2]是数据长度
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes Data = 3 [default = ""];</code>
     *
     * <pre>
     * 数据, data[0:2]是数据长度
     * </pre>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protocol_v1.V1Structured.Structured parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Structured.Structured parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Structured.Structured parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Structured.Structured parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Structured.Structured parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Structured.Structured parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Structured.Structured parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol_v1.V1Structured.Structured parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Structured.Structured parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Structured.Structured parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol_v1.V1Structured.Structured prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.Structured}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.Structured)
        protocol_v1.V1Structured.StructuredOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol_v1.V1Structured.internal_static_protocol_v1_Structured_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol_v1.V1Structured.internal_static_protocol_v1_Structured_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol_v1.V1Structured.Structured.class, protocol_v1.V1Structured.Structured.Builder.class);
      }

      // Construct using protocol_v1.V1Structured.Structured.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.Internal.bytesDefaultValue("");
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol_v1.V1Structured.internal_static_protocol_v1_Structured_descriptor;
      }

      public protocol_v1.V1Structured.Structured getDefaultInstanceForType() {
        return protocol_v1.V1Structured.Structured.getDefaultInstance();
      }

      public protocol_v1.V1Structured.Structured build() {
        protocol_v1.V1Structured.Structured result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol_v1.V1Structured.Structured buildPartial() {
        protocol_v1.V1Structured.Structured result = new protocol_v1.V1Structured.Structured(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol_v1.V1Structured.Structured) {
          return mergeFrom((protocol_v1.V1Structured.Structured)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol_v1.V1Structured.Structured other) {
        if (other == protocol_v1.V1Structured.Structured.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol_v1.V1Structured.Structured parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol_v1.V1Structured.Structured) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int timestamp_ ;
      /**
       * <code>optional uint32 Timestamp = 1 [default = 0];</code>
       *
       * <pre>
       * 采集时间, unix时间戳
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 Timestamp = 1 [default = 0];</code>
       *
       * <pre>
       * 采集时间, unix时间戳
       * </pre>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint32 Timestamp = 1 [default = 0];</code>
       *
       * <pre>
       * 采集时间, unix时间戳
       * </pre>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 Timestamp = 1 [default = 0];</code>
       *
       * <pre>
       * 采集时间, unix时间戳
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 Type = 2 [default = 0];</code>
       *
       * <pre>
       * 类型, 1:于辉算法  11:以色列4s odba
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 Type = 2 [default = 0];</code>
       *
       * <pre>
       * 类型, 1:于辉算法  11:以色列4s odba
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 Type = 2 [default = 0];</code>
       *
       * <pre>
       * 类型, 1:于辉算法  11:以色列4s odba
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Type = 2 [default = 0];</code>
       *
       * <pre>
       * 类型, 1:于辉算法  11:以色列4s odba
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.Internal.bytesDefaultValue("");
      /**
       * <code>optional bytes Data = 3 [default = ""];</code>
       *
       * <pre>
       * 数据, data[0:2]是数据长度
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes Data = 3 [default = ""];</code>
       *
       * <pre>
       * 数据, data[0:2]是数据长度
       * </pre>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes Data = 3 [default = ""];</code>
       *
       * <pre>
       * 数据, data[0:2]是数据长度
       * </pre>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes Data = 3 [default = ""];</code>
       *
       * <pre>
       * 数据, data[0:2]是数据长度
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol_v1.Structured)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.Structured)
    private static final protocol_v1.V1Structured.Structured DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol_v1.V1Structured.Structured();
    }

    public static protocol_v1.V1Structured.Structured getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Structured>
        PARSER = new com.google.protobuf.AbstractParser<Structured>() {
      public Structured parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Structured(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Structured> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Structured> getParserForType() {
      return PARSER;
    }

    public protocol_v1.V1Structured.Structured getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StructuredReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.StructuredReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     *
     * <pre>
     * 身份验证
     * </pre>
     */
    boolean hasIden();
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     *
     * <pre>
     * 身份验证
     * </pre>
     */
    protocol_v1.V1IdentityMsg.IdentityMsg getIden();
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     *
     * <pre>
     * 身份验证
     * </pre>
     */
    protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder getIdenOrBuilder();

    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    java.util.List<protocol_v1.V1Structured.Structured> 
        getStructuredInfoList();
    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    protocol_v1.V1Structured.Structured getStructuredInfo(int index);
    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    int getStructuredInfoCount();
    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    java.util.List<? extends protocol_v1.V1Structured.StructuredOrBuilder> 
        getStructuredInfoOrBuilderList();
    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    protocol_v1.V1Structured.StructuredOrBuilder getStructuredInfoOrBuilder(
        int index);

    /**
     * <code>optional int32 Version = 10 [default = 0];</code>
     *
     * <pre>
     * 数据版本
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional int32 Version = 10 [default = 0];</code>
     *
     * <pre>
     * 数据版本
     * </pre>
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code protocol_v1.StructuredReq}
   */
  public  static final class StructuredReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol_v1.StructuredReq)
      StructuredReqOrBuilder {
    // Use StructuredReq.newBuilder() to construct.
    private StructuredReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private StructuredReq() {
      structuredInfo_ = java.util.Collections.emptyList();
      version_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StructuredReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol_v1.V1IdentityMsg.IdentityMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = iden_.toBuilder();
              }
              iden_ = input.readMessage(protocol_v1.V1IdentityMsg.IdentityMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(iden_);
                iden_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                structuredInfo_ = new java.util.ArrayList<protocol_v1.V1Structured.Structured>();
                mutable_bitField0_ |= 0x00000002;
              }
              structuredInfo_.add(input.readMessage(protocol_v1.V1Structured.Structured.parser(), extensionRegistry));
              break;
            }
            case 80: {
              bitField0_ |= 0x00000002;
              version_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          structuredInfo_ = java.util.Collections.unmodifiableList(structuredInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_v1.V1Structured.internal_static_protocol_v1_StructuredReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_v1.V1Structured.internal_static_protocol_v1_StructuredReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_v1.V1Structured.StructuredReq.class, protocol_v1.V1Structured.StructuredReq.Builder.class);
    }

    private int bitField0_;
    public static final int IDEN_FIELD_NUMBER = 1;
    private protocol_v1.V1IdentityMsg.IdentityMsg iden_;
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     *
     * <pre>
     * 身份验证
     * </pre>
     */
    public boolean hasIden() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     *
     * <pre>
     * 身份验证
     * </pre>
     */
    public protocol_v1.V1IdentityMsg.IdentityMsg getIden() {
      return iden_ == null ? protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance() : iden_;
    }
    /**
     * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
     *
     * <pre>
     * 身份验证
     * </pre>
     */
    public protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder getIdenOrBuilder() {
      return iden_ == null ? protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance() : iden_;
    }

    public static final int STRUCTUREDINFO_FIELD_NUMBER = 2;
    private java.util.List<protocol_v1.V1Structured.Structured> structuredInfo_;
    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    public java.util.List<protocol_v1.V1Structured.Structured> getStructuredInfoList() {
      return structuredInfo_;
    }
    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    public java.util.List<? extends protocol_v1.V1Structured.StructuredOrBuilder> 
        getStructuredInfoOrBuilderList() {
      return structuredInfo_;
    }
    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    public int getStructuredInfoCount() {
      return structuredInfo_.size();
    }
    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    public protocol_v1.V1Structured.Structured getStructuredInfo(int index) {
      return structuredInfo_.get(index);
    }
    /**
     * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
     *
     * <pre>
     * 结构化数据
     * </pre>
     */
    public protocol_v1.V1Structured.StructuredOrBuilder getStructuredInfoOrBuilder(
        int index) {
      return structuredInfo_.get(index);
    }

    public static final int VERSION_FIELD_NUMBER = 10;
    private int version_;
    /**
     * <code>optional int32 Version = 10 [default = 0];</code>
     *
     * <pre>
     * 数据版本
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 Version = 10 [default = 0];</code>
     *
     * <pre>
     * 数据版本
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIden()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getIden().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getIden());
      }
      for (int i = 0; i < structuredInfo_.size(); i++) {
        output.writeMessage(2, structuredInfo_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(10, version_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getIden());
      }
      for (int i = 0; i < structuredInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, structuredInfo_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protocol_v1.V1Structured.StructuredReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Structured.StructuredReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Structured.StructuredReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Structured.StructuredReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Structured.StructuredReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Structured.StructuredReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Structured.StructuredReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol_v1.V1Structured.StructuredReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Structured.StructuredReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Structured.StructuredReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol_v1.V1Structured.StructuredReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.StructuredReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.StructuredReq)
        protocol_v1.V1Structured.StructuredReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol_v1.V1Structured.internal_static_protocol_v1_StructuredReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol_v1.V1Structured.internal_static_protocol_v1_StructuredReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol_v1.V1Structured.StructuredReq.class, protocol_v1.V1Structured.StructuredReq.Builder.class);
      }

      // Construct using protocol_v1.V1Structured.StructuredReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIdenFieldBuilder();
          getStructuredInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (idenBuilder_ == null) {
          iden_ = null;
        } else {
          idenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (structuredInfoBuilder_ == null) {
          structuredInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          structuredInfoBuilder_.clear();
        }
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol_v1.V1Structured.internal_static_protocol_v1_StructuredReq_descriptor;
      }

      public protocol_v1.V1Structured.StructuredReq getDefaultInstanceForType() {
        return protocol_v1.V1Structured.StructuredReq.getDefaultInstance();
      }

      public protocol_v1.V1Structured.StructuredReq build() {
        protocol_v1.V1Structured.StructuredReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol_v1.V1Structured.StructuredReq buildPartial() {
        protocol_v1.V1Structured.StructuredReq result = new protocol_v1.V1Structured.StructuredReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (idenBuilder_ == null) {
          result.iden_ = iden_;
        } else {
          result.iden_ = idenBuilder_.build();
        }
        if (structuredInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            structuredInfo_ = java.util.Collections.unmodifiableList(structuredInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.structuredInfo_ = structuredInfo_;
        } else {
          result.structuredInfo_ = structuredInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol_v1.V1Structured.StructuredReq) {
          return mergeFrom((protocol_v1.V1Structured.StructuredReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol_v1.V1Structured.StructuredReq other) {
        if (other == protocol_v1.V1Structured.StructuredReq.getDefaultInstance()) return this;
        if (other.hasIden()) {
          mergeIden(other.getIden());
        }
        if (structuredInfoBuilder_ == null) {
          if (!other.structuredInfo_.isEmpty()) {
            if (structuredInfo_.isEmpty()) {
              structuredInfo_ = other.structuredInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStructuredInfoIsMutable();
              structuredInfo_.addAll(other.structuredInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.structuredInfo_.isEmpty()) {
            if (structuredInfoBuilder_.isEmpty()) {
              structuredInfoBuilder_.dispose();
              structuredInfoBuilder_ = null;
              structuredInfo_ = other.structuredInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              structuredInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStructuredInfoFieldBuilder() : null;
            } else {
              structuredInfoBuilder_.addAllMessages(other.structuredInfo_);
            }
          }
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIden()) {
          return false;
        }
        if (!getIden().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol_v1.V1Structured.StructuredReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol_v1.V1Structured.StructuredReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol_v1.V1IdentityMsg.IdentityMsg iden_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          protocol_v1.V1IdentityMsg.IdentityMsg, protocol_v1.V1IdentityMsg.IdentityMsg.Builder, protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder> idenBuilder_;
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       *
       * <pre>
       * 身份验证
       * </pre>
       */
      public boolean hasIden() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       *
       * <pre>
       * 身份验证
       * </pre>
       */
      public protocol_v1.V1IdentityMsg.IdentityMsg getIden() {
        if (idenBuilder_ == null) {
          return iden_ == null ? protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance() : iden_;
        } else {
          return idenBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       *
       * <pre>
       * 身份验证
       * </pre>
       */
      public Builder setIden(protocol_v1.V1IdentityMsg.IdentityMsg value) {
        if (idenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          iden_ = value;
          onChanged();
        } else {
          idenBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       *
       * <pre>
       * 身份验证
       * </pre>
       */
      public Builder setIden(
          protocol_v1.V1IdentityMsg.IdentityMsg.Builder builderForValue) {
        if (idenBuilder_ == null) {
          iden_ = builderForValue.build();
          onChanged();
        } else {
          idenBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       *
       * <pre>
       * 身份验证
       * </pre>
       */
      public Builder mergeIden(protocol_v1.V1IdentityMsg.IdentityMsg value) {
        if (idenBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              iden_ != null &&
              iden_ != protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance()) {
            iden_ =
              protocol_v1.V1IdentityMsg.IdentityMsg.newBuilder(iden_).mergeFrom(value).buildPartial();
          } else {
            iden_ = value;
          }
          onChanged();
        } else {
          idenBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       *
       * <pre>
       * 身份验证
       * </pre>
       */
      public Builder clearIden() {
        if (idenBuilder_ == null) {
          iden_ = null;
          onChanged();
        } else {
          idenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       *
       * <pre>
       * 身份验证
       * </pre>
       */
      public protocol_v1.V1IdentityMsg.IdentityMsg.Builder getIdenBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdenFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       *
       * <pre>
       * 身份验证
       * </pre>
       */
      public protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder getIdenOrBuilder() {
        if (idenBuilder_ != null) {
          return idenBuilder_.getMessageOrBuilder();
        } else {
          return iden_ == null ?
              protocol_v1.V1IdentityMsg.IdentityMsg.getDefaultInstance() : iden_;
        }
      }
      /**
       * <code>required .protocol_v1.IdentityMsg Iden = 1;</code>
       *
       * <pre>
       * 身份验证
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol_v1.V1IdentityMsg.IdentityMsg, protocol_v1.V1IdentityMsg.IdentityMsg.Builder, protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder> 
          getIdenFieldBuilder() {
        if (idenBuilder_ == null) {
          idenBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol_v1.V1IdentityMsg.IdentityMsg, protocol_v1.V1IdentityMsg.IdentityMsg.Builder, protocol_v1.V1IdentityMsg.IdentityMsgOrBuilder>(
                  getIden(),
                  getParentForChildren(),
                  isClean());
          iden_ = null;
        }
        return idenBuilder_;
      }

      private java.util.List<protocol_v1.V1Structured.Structured> structuredInfo_ =
        java.util.Collections.emptyList();
      private void ensureStructuredInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          structuredInfo_ = new java.util.ArrayList<protocol_v1.V1Structured.Structured>(structuredInfo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protocol_v1.V1Structured.Structured, protocol_v1.V1Structured.Structured.Builder, protocol_v1.V1Structured.StructuredOrBuilder> structuredInfoBuilder_;

      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public java.util.List<protocol_v1.V1Structured.Structured> getStructuredInfoList() {
        if (structuredInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(structuredInfo_);
        } else {
          return structuredInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public int getStructuredInfoCount() {
        if (structuredInfoBuilder_ == null) {
          return structuredInfo_.size();
        } else {
          return structuredInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public protocol_v1.V1Structured.Structured getStructuredInfo(int index) {
        if (structuredInfoBuilder_ == null) {
          return structuredInfo_.get(index);
        } else {
          return structuredInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public Builder setStructuredInfo(
          int index, protocol_v1.V1Structured.Structured value) {
        if (structuredInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStructuredInfoIsMutable();
          structuredInfo_.set(index, value);
          onChanged();
        } else {
          structuredInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public Builder setStructuredInfo(
          int index, protocol_v1.V1Structured.Structured.Builder builderForValue) {
        if (structuredInfoBuilder_ == null) {
          ensureStructuredInfoIsMutable();
          structuredInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          structuredInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public Builder addStructuredInfo(protocol_v1.V1Structured.Structured value) {
        if (structuredInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStructuredInfoIsMutable();
          structuredInfo_.add(value);
          onChanged();
        } else {
          structuredInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public Builder addStructuredInfo(
          int index, protocol_v1.V1Structured.Structured value) {
        if (structuredInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStructuredInfoIsMutable();
          structuredInfo_.add(index, value);
          onChanged();
        } else {
          structuredInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public Builder addStructuredInfo(
          protocol_v1.V1Structured.Structured.Builder builderForValue) {
        if (structuredInfoBuilder_ == null) {
          ensureStructuredInfoIsMutable();
          structuredInfo_.add(builderForValue.build());
          onChanged();
        } else {
          structuredInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public Builder addStructuredInfo(
          int index, protocol_v1.V1Structured.Structured.Builder builderForValue) {
        if (structuredInfoBuilder_ == null) {
          ensureStructuredInfoIsMutable();
          structuredInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          structuredInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public Builder addAllStructuredInfo(
          java.lang.Iterable<? extends protocol_v1.V1Structured.Structured> values) {
        if (structuredInfoBuilder_ == null) {
          ensureStructuredInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, structuredInfo_);
          onChanged();
        } else {
          structuredInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public Builder clearStructuredInfo() {
        if (structuredInfoBuilder_ == null) {
          structuredInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          structuredInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public Builder removeStructuredInfo(int index) {
        if (structuredInfoBuilder_ == null) {
          ensureStructuredInfoIsMutable();
          structuredInfo_.remove(index);
          onChanged();
        } else {
          structuredInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public protocol_v1.V1Structured.Structured.Builder getStructuredInfoBuilder(
          int index) {
        return getStructuredInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public protocol_v1.V1Structured.StructuredOrBuilder getStructuredInfoOrBuilder(
          int index) {
        if (structuredInfoBuilder_ == null) {
          return structuredInfo_.get(index);  } else {
          return structuredInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public java.util.List<? extends protocol_v1.V1Structured.StructuredOrBuilder> 
           getStructuredInfoOrBuilderList() {
        if (structuredInfoBuilder_ != null) {
          return structuredInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(structuredInfo_);
        }
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public protocol_v1.V1Structured.Structured.Builder addStructuredInfoBuilder() {
        return getStructuredInfoFieldBuilder().addBuilder(
            protocol_v1.V1Structured.Structured.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public protocol_v1.V1Structured.Structured.Builder addStructuredInfoBuilder(
          int index) {
        return getStructuredInfoFieldBuilder().addBuilder(
            index, protocol_v1.V1Structured.Structured.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol_v1.Structured StructuredInfo = 2;</code>
       *
       * <pre>
       * 结构化数据
       * </pre>
       */
      public java.util.List<protocol_v1.V1Structured.Structured.Builder> 
           getStructuredInfoBuilderList() {
        return getStructuredInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol_v1.V1Structured.Structured, protocol_v1.V1Structured.Structured.Builder, protocol_v1.V1Structured.StructuredOrBuilder> 
          getStructuredInfoFieldBuilder() {
        if (structuredInfoBuilder_ == null) {
          structuredInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protocol_v1.V1Structured.Structured, protocol_v1.V1Structured.Structured.Builder, protocol_v1.V1Structured.StructuredOrBuilder>(
                  structuredInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          structuredInfo_ = null;
        }
        return structuredInfoBuilder_;
      }

      private int version_ ;
      /**
       * <code>optional int32 Version = 10 [default = 0];</code>
       *
       * <pre>
       * 数据版本
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 Version = 10 [default = 0];</code>
       *
       * <pre>
       * 数据版本
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 Version = 10 [default = 0];</code>
       *
       * <pre>
       * 数据版本
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Version = 10 [default = 0];</code>
       *
       * <pre>
       * 数据版本
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol_v1.StructuredReq)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.StructuredReq)
    private static final protocol_v1.V1Structured.StructuredReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol_v1.V1Structured.StructuredReq();
    }

    public static protocol_v1.V1Structured.StructuredReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<StructuredReq>
        PARSER = new com.google.protobuf.AbstractParser<StructuredReq>() {
      public StructuredReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new StructuredReq(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<StructuredReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StructuredReq> getParserForType() {
      return PARSER;
    }

    public protocol_v1.V1Structured.StructuredReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_Structured_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_v1_Structured_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_StructuredReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_v1_StructuredReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023v1.Structured.proto\022\013protocol_v1\032\024v1.I" +
      "dentityMsg.proto\"C\n\nStructured\022\024\n\tTimest" +
      "amp\030\001 \001(\r:\0010\022\017\n\004Type\030\002 \001(\005:\0010\022\016\n\004Data\030\003 " +
      "\001(\014:\000\"|\n\rStructuredReq\022&\n\004Iden\030\001 \002(\0132\030.p" +
      "rotocol_v1.IdentityMsg\022/\n\016StructuredInfo" +
      "\030\002 \003(\0132\027.protocol_v1.Structured\022\022\n\007Versi" +
      "on\030\n \001(\005:\0010B\005\242\002\002V1"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol_v1.V1IdentityMsg.getDescriptor(),
        }, assigner);
    internal_static_protocol_v1_Structured_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_v1_Structured_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_v1_Structured_descriptor,
        new java.lang.String[] { "Timestamp", "Type", "Data", });
    internal_static_protocol_v1_StructuredReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_v1_StructuredReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_v1_StructuredReq_descriptor,
        new java.lang.String[] { "Iden", "StructuredInfo", "Version", });
    protocol_v1.V1IdentityMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
