// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1.Switch.proto

package protocol_v1;

public final class V1Switch {
  private V1Switch() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SwitchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol_v1.Switch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 Mode = 1 [default = 0];</code>
     *
     * <pre>
     * 0 - disable, 1 - 定时上传, 2 - 持续在线,一直回传(适合eDRX), 101 - 整点回传
     * </pre>
     */
    boolean hasMode();
    /**
     * <code>optional int32 Mode = 1 [default = 0];</code>
     *
     * <pre>
     * 0 - disable, 1 - 定时上传, 2 - 持续在线,一直回传(适合eDRX), 101 - 整点回传
     * </pre>
     */
    int getMode();

    /**
     * <code>optional int32 Interval = 2 [default = 0];</code>
     *
     * <pre>
     * 采样频率: 单位(s)
     * </pre>
     */
    boolean hasInterval();
    /**
     * <code>optional int32 Interval = 2 [default = 0];</code>
     *
     * <pre>
     * 采样频率: 单位(s)
     * </pre>
     */
    int getInterval();

    /**
     * <code>optional uint32 TimeTable = 3 [default = 0];</code>
     *
     * <pre>
     * 准点回传时间表
     * </pre>
     */
    boolean hasTimeTable();
    /**
     * <code>optional uint32 TimeTable = 3 [default = 0];</code>
     *
     * <pre>
     * 准点回传时间表
     * </pre>
     */
    int getTimeTable();
  }
  /**
   * Protobuf type {@code protocol_v1.Switch}
   */
  public  static final class Switch extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protocol_v1.Switch)
      SwitchOrBuilder {
    // Use Switch.newBuilder() to construct.
    private Switch(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Switch() {
      mode_ = 0;
      interval_ = 0;
      timeTable_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Switch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              interval_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeTable_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol_v1.V1Switch.internal_static_protocol_v1_Switch_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol_v1.V1Switch.internal_static_protocol_v1_Switch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol_v1.V1Switch.Switch.class, protocol_v1.V1Switch.Switch.Builder.class);
    }

    private int bitField0_;
    public static final int MODE_FIELD_NUMBER = 1;
    private int mode_;
    /**
     * <code>optional int32 Mode = 1 [default = 0];</code>
     *
     * <pre>
     * 0 - disable, 1 - 定时上传, 2 - 持续在线,一直回传(适合eDRX), 101 - 整点回传
     * </pre>
     */
    public boolean hasMode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 Mode = 1 [default = 0];</code>
     *
     * <pre>
     * 0 - disable, 1 - 定时上传, 2 - 持续在线,一直回传(适合eDRX), 101 - 整点回传
     * </pre>
     */
    public int getMode() {
      return mode_;
    }

    public static final int INTERVAL_FIELD_NUMBER = 2;
    private int interval_;
    /**
     * <code>optional int32 Interval = 2 [default = 0];</code>
     *
     * <pre>
     * 采样频率: 单位(s)
     * </pre>
     */
    public boolean hasInterval() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 Interval = 2 [default = 0];</code>
     *
     * <pre>
     * 采样频率: 单位(s)
     * </pre>
     */
    public int getInterval() {
      return interval_;
    }

    public static final int TIMETABLE_FIELD_NUMBER = 3;
    private int timeTable_;
    /**
     * <code>optional uint32 TimeTable = 3 [default = 0];</code>
     *
     * <pre>
     * 准点回传时间表
     * </pre>
     */
    public boolean hasTimeTable() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 TimeTable = 3 [default = 0];</code>
     *
     * <pre>
     * 准点回传时间表
     * </pre>
     */
    public int getTimeTable() {
      return timeTable_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, mode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, interval_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, timeTable_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, interval_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, timeTable_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protocol_v1.V1Switch.Switch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Switch.Switch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Switch.Switch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol_v1.V1Switch.Switch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol_v1.V1Switch.Switch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Switch.Switch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Switch.Switch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol_v1.V1Switch.Switch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol_v1.V1Switch.Switch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol_v1.V1Switch.Switch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol_v1.V1Switch.Switch prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol_v1.Switch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol_v1.Switch)
        protocol_v1.V1Switch.SwitchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol_v1.V1Switch.internal_static_protocol_v1_Switch_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol_v1.V1Switch.internal_static_protocol_v1_Switch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol_v1.V1Switch.Switch.class, protocol_v1.V1Switch.Switch.Builder.class);
      }

      // Construct using protocol_v1.V1Switch.Switch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        interval_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeTable_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol_v1.V1Switch.internal_static_protocol_v1_Switch_descriptor;
      }

      public protocol_v1.V1Switch.Switch getDefaultInstanceForType() {
        return protocol_v1.V1Switch.Switch.getDefaultInstance();
      }

      public protocol_v1.V1Switch.Switch build() {
        protocol_v1.V1Switch.Switch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol_v1.V1Switch.Switch buildPartial() {
        protocol_v1.V1Switch.Switch result = new protocol_v1.V1Switch.Switch(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mode_ = mode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.interval_ = interval_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeTable_ = timeTable_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol_v1.V1Switch.Switch) {
          return mergeFrom((protocol_v1.V1Switch.Switch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol_v1.V1Switch.Switch other) {
        if (other == protocol_v1.V1Switch.Switch.getDefaultInstance()) return this;
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        if (other.hasInterval()) {
          setInterval(other.getInterval());
        }
        if (other.hasTimeTable()) {
          setTimeTable(other.getTimeTable());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol_v1.V1Switch.Switch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol_v1.V1Switch.Switch) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int mode_ ;
      /**
       * <code>optional int32 Mode = 1 [default = 0];</code>
       *
       * <pre>
       * 0 - disable, 1 - 定时上传, 2 - 持续在线,一直回传(适合eDRX), 101 - 整点回传
       * </pre>
       */
      public boolean hasMode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 Mode = 1 [default = 0];</code>
       *
       * <pre>
       * 0 - disable, 1 - 定时上传, 2 - 持续在线,一直回传(适合eDRX), 101 - 整点回传
       * </pre>
       */
      public int getMode() {
        return mode_;
      }
      /**
       * <code>optional int32 Mode = 1 [default = 0];</code>
       *
       * <pre>
       * 0 - disable, 1 - 定时上传, 2 - 持续在线,一直回传(适合eDRX), 101 - 整点回传
       * </pre>
       */
      public Builder setMode(int value) {
        bitField0_ |= 0x00000001;
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Mode = 1 [default = 0];</code>
       *
       * <pre>
       * 0 - disable, 1 - 定时上传, 2 - 持续在线,一直回传(适合eDRX), 101 - 整点回传
       * </pre>
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mode_ = 0;
        onChanged();
        return this;
      }

      private int interval_ ;
      /**
       * <code>optional int32 Interval = 2 [default = 0];</code>
       *
       * <pre>
       * 采样频率: 单位(s)
       * </pre>
       */
      public boolean hasInterval() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 Interval = 2 [default = 0];</code>
       *
       * <pre>
       * 采样频率: 单位(s)
       * </pre>
       */
      public int getInterval() {
        return interval_;
      }
      /**
       * <code>optional int32 Interval = 2 [default = 0];</code>
       *
       * <pre>
       * 采样频率: 单位(s)
       * </pre>
       */
      public Builder setInterval(int value) {
        bitField0_ |= 0x00000002;
        interval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Interval = 2 [default = 0];</code>
       *
       * <pre>
       * 采样频率: 单位(s)
       * </pre>
       */
      public Builder clearInterval() {
        bitField0_ = (bitField0_ & ~0x00000002);
        interval_ = 0;
        onChanged();
        return this;
      }

      private int timeTable_ ;
      /**
       * <code>optional uint32 TimeTable = 3 [default = 0];</code>
       *
       * <pre>
       * 准点回传时间表
       * </pre>
       */
      public boolean hasTimeTable() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 TimeTable = 3 [default = 0];</code>
       *
       * <pre>
       * 准点回传时间表
       * </pre>
       */
      public int getTimeTable() {
        return timeTable_;
      }
      /**
       * <code>optional uint32 TimeTable = 3 [default = 0];</code>
       *
       * <pre>
       * 准点回传时间表
       * </pre>
       */
      public Builder setTimeTable(int value) {
        bitField0_ |= 0x00000004;
        timeTable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 TimeTable = 3 [default = 0];</code>
       *
       * <pre>
       * 准点回传时间表
       * </pre>
       */
      public Builder clearTimeTable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeTable_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol_v1.Switch)
    }

    // @@protoc_insertion_point(class_scope:protocol_v1.Switch)
    private static final protocol_v1.V1Switch.Switch DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol_v1.V1Switch.Switch();
    }

    public static protocol_v1.V1Switch.Switch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Switch>
        PARSER = new com.google.protobuf.AbstractParser<Switch>() {
      public Switch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Switch(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Switch> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Switch> getParserForType() {
      return PARSER;
    }

    public protocol_v1.V1Switch.Switch getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_v1_Switch_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_v1_Switch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017v1.Switch.proto\022\013protocol_v1\"D\n\006Switch" +
      "\022\017\n\004Mode\030\001 \001(\005:\0010\022\023\n\010Interval\030\002 \001(\005:\0010\022\024" +
      "\n\tTimeTable\030\003 \001(\r:\0010B\005\242\002\002V1"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_v1_Switch_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_v1_Switch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_v1_Switch_descriptor,
        new java.lang.String[] { "Mode", "Interval", "TimeTable", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
