// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Download.proto

package protocol;

public final class Download {
  private Download() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DownloadReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.DownloadReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protocol.IdentityMsg Iden = 1;</code>
     */
    boolean hasIden();
    /**
     * <code>required .protocol.IdentityMsg Iden = 1;</code>
     */
    protocol.IdentityMsgOuterClass.IdentityMsg getIden();
    /**
     * <code>required .protocol.IdentityMsg Iden = 1;</code>
     */
    protocol.IdentityMsgOuterClass.IdentityMsgOrBuilder getIdenOrBuilder();

    /**
     * <pre>
     * firmware id
     * </pre>
     *
     * <code>optional string FileId = 2 [default = ""];</code>
     */
    boolean hasFileId();
    /**
     * <pre>
     * firmware id
     * </pre>
     *
     * <code>optional string FileId = 2 [default = ""];</code>
     */
    String getFileId();
    /**
     * <pre>
     * firmware id
     * </pre>
     *
     * <code>optional string FileId = 2 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getFileIdBytes();

    /**
     * <pre>
     * 固件开始位置
     * </pre>
     *
     * <code>optional int32 Begin = 3 [default = 0];</code>
     */
    boolean hasBegin();
    /**
     * <pre>
     * 固件开始位置
     * </pre>
     *
     * <code>optional int32 Begin = 3 [default = 0];</code>
     */
    int getBegin();

    /**
     * <pre>
     * 回传固件长度限制
     * </pre>
     *
     * <code>optional int32 Length = 4 [default = 1400];</code>
     */
    boolean hasLength();
    /**
     * <pre>
     * 回传固件长度限制
     * </pre>
     *
     * <code>optional int32 Length = 4 [default = 1400];</code>
     */
    int getLength();
  }
  /**
   * Protobuf type {@code protocol.DownloadReq}
   */
  public  static final class DownloadReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.DownloadReq)
      DownloadReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DownloadReq.newBuilder() to construct.
    private DownloadReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DownloadReq() {
      fileId_ = "";
      length_ = 1400;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DownloadReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              protocol.IdentityMsgOuterClass.IdentityMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = iden_.toBuilder();
              }
              iden_ = input.readMessage(protocol.IdentityMsgOuterClass.IdentityMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(iden_);
                iden_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              fileId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              begin_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              length_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Download.internal_static_protocol_DownloadReq_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Download.internal_static_protocol_DownloadReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DownloadReq.class, Builder.class);
    }

    private int bitField0_;
    public static final int IDEN_FIELD_NUMBER = 1;
    private protocol.IdentityMsgOuterClass.IdentityMsg iden_;
    /**
     * <code>required .protocol.IdentityMsg Iden = 1;</code>
     */
    public boolean hasIden() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protocol.IdentityMsg Iden = 1;</code>
     */
    public protocol.IdentityMsgOuterClass.IdentityMsg getIden() {
      return iden_ == null ? protocol.IdentityMsgOuterClass.IdentityMsg.getDefaultInstance() : iden_;
    }
    /**
     * <code>required .protocol.IdentityMsg Iden = 1;</code>
     */
    public protocol.IdentityMsgOuterClass.IdentityMsgOrBuilder getIdenOrBuilder() {
      return iden_ == null ? protocol.IdentityMsgOuterClass.IdentityMsg.getDefaultInstance() : iden_;
    }

    public static final int FILEID_FIELD_NUMBER = 2;
    private volatile Object fileId_;
    /**
     * <pre>
     * firmware id
     * </pre>
     *
     * <code>optional string FileId = 2 [default = ""];</code>
     */
    public boolean hasFileId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * firmware id
     * </pre>
     *
     * <code>optional string FileId = 2 [default = ""];</code>
     */
    public String getFileId() {
      Object ref = fileId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * firmware id
     * </pre>
     *
     * <code>optional string FileId = 2 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getFileIdBytes() {
      Object ref = fileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BEGIN_FIELD_NUMBER = 3;
    private int begin_;
    /**
     * <pre>
     * 固件开始位置
     * </pre>
     *
     * <code>optional int32 Begin = 3 [default = 0];</code>
     */
    public boolean hasBegin() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 固件开始位置
     * </pre>
     *
     * <code>optional int32 Begin = 3 [default = 0];</code>
     */
    public int getBegin() {
      return begin_;
    }

    public static final int LENGTH_FIELD_NUMBER = 4;
    private int length_;
    /**
     * <pre>
     * 回传固件长度限制
     * </pre>
     *
     * <code>optional int32 Length = 4 [default = 1400];</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 回传固件长度限制
     * </pre>
     *
     * <code>optional int32 Length = 4 [default = 1400];</code>
     */
    public int getLength() {
      return length_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIden()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getIden().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getIden());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, begin_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, length_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getIden());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, begin_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, length_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DownloadReq)) {
        return super.equals(obj);
      }
      DownloadReq other = (DownloadReq) obj;

      if (hasIden() != other.hasIden()) return false;
      if (hasIden()) {
        if (!getIden()
            .equals(other.getIden())) return false;
      }
      if (hasFileId() != other.hasFileId()) return false;
      if (hasFileId()) {
        if (!getFileId()
            .equals(other.getFileId())) return false;
      }
      if (hasBegin() != other.hasBegin()) return false;
      if (hasBegin()) {
        if (getBegin()
            != other.getBegin()) return false;
      }
      if (hasLength() != other.hasLength()) return false;
      if (hasLength()) {
        if (getLength()
            != other.getLength()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIden()) {
        hash = (37 * hash) + IDEN_FIELD_NUMBER;
        hash = (53 * hash) + getIden().hashCode();
      }
      if (hasFileId()) {
        hash = (37 * hash) + FILEID_FIELD_NUMBER;
        hash = (53 * hash) + getFileId().hashCode();
      }
      if (hasBegin()) {
        hash = (37 * hash) + BEGIN_FIELD_NUMBER;
        hash = (53 * hash) + getBegin();
      }
      if (hasLength()) {
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getLength();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DownloadReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DownloadReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DownloadReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DownloadReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DownloadReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DownloadReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DownloadReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DownloadReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DownloadReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DownloadReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DownloadReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DownloadReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DownloadReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.DownloadReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.DownloadReq)
        DownloadReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Download.internal_static_protocol_DownloadReq_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Download.internal_static_protocol_DownloadReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DownloadReq.class, Builder.class);
      }

      // Construct using protocol.Download.DownloadReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIdenFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (idenBuilder_ == null) {
          iden_ = null;
        } else {
          idenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        fileId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        begin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = 1400;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Download.internal_static_protocol_DownloadReq_descriptor;
      }

      @Override
      public DownloadReq getDefaultInstanceForType() {
        return DownloadReq.getDefaultInstance();
      }

      @Override
      public DownloadReq build() {
        DownloadReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DownloadReq buildPartial() {
        DownloadReq result = new DownloadReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (idenBuilder_ == null) {
            result.iden_ = iden_;
          } else {
            result.iden_ = idenBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileId_ = fileId_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.begin_ = begin_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.length_ = length_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DownloadReq) {
          return mergeFrom((DownloadReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DownloadReq other) {
        if (other == DownloadReq.getDefaultInstance()) return this;
        if (other.hasIden()) {
          mergeIden(other.getIden());
        }
        if (other.hasFileId()) {
          bitField0_ |= 0x00000002;
          fileId_ = other.fileId_;
          onChanged();
        }
        if (other.hasBegin()) {
          setBegin(other.getBegin());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasIden()) {
          return false;
        }
        if (!getIden().isInitialized()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DownloadReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DownloadReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol.IdentityMsgOuterClass.IdentityMsg iden_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.IdentityMsgOuterClass.IdentityMsg, protocol.IdentityMsgOuterClass.IdentityMsg.Builder, protocol.IdentityMsgOuterClass.IdentityMsgOrBuilder> idenBuilder_;
      /**
       * <code>required .protocol.IdentityMsg Iden = 1;</code>
       */
      public boolean hasIden() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .protocol.IdentityMsg Iden = 1;</code>
       */
      public protocol.IdentityMsgOuterClass.IdentityMsg getIden() {
        if (idenBuilder_ == null) {
          return iden_ == null ? protocol.IdentityMsgOuterClass.IdentityMsg.getDefaultInstance() : iden_;
        } else {
          return idenBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol.IdentityMsg Iden = 1;</code>
       */
      public Builder setIden(protocol.IdentityMsgOuterClass.IdentityMsg value) {
        if (idenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          iden_ = value;
          onChanged();
        } else {
          idenBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.IdentityMsg Iden = 1;</code>
       */
      public Builder setIden(
          protocol.IdentityMsgOuterClass.IdentityMsg.Builder builderForValue) {
        if (idenBuilder_ == null) {
          iden_ = builderForValue.build();
          onChanged();
        } else {
          idenBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.IdentityMsg Iden = 1;</code>
       */
      public Builder mergeIden(protocol.IdentityMsgOuterClass.IdentityMsg value) {
        if (idenBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              iden_ != null &&
              iden_ != protocol.IdentityMsgOuterClass.IdentityMsg.getDefaultInstance()) {
            iden_ =
              protocol.IdentityMsgOuterClass.IdentityMsg.newBuilder(iden_).mergeFrom(value).buildPartial();
          } else {
            iden_ = value;
          }
          onChanged();
        } else {
          idenBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.IdentityMsg Iden = 1;</code>
       */
      public Builder clearIden() {
        if (idenBuilder_ == null) {
          iden_ = null;
          onChanged();
        } else {
          idenBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protocol.IdentityMsg Iden = 1;</code>
       */
      public protocol.IdentityMsgOuterClass.IdentityMsg.Builder getIdenBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdenFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol.IdentityMsg Iden = 1;</code>
       */
      public protocol.IdentityMsgOuterClass.IdentityMsgOrBuilder getIdenOrBuilder() {
        if (idenBuilder_ != null) {
          return idenBuilder_.getMessageOrBuilder();
        } else {
          return iden_ == null ?
              protocol.IdentityMsgOuterClass.IdentityMsg.getDefaultInstance() : iden_;
        }
      }
      /**
       * <code>required .protocol.IdentityMsg Iden = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.IdentityMsgOuterClass.IdentityMsg, protocol.IdentityMsgOuterClass.IdentityMsg.Builder, protocol.IdentityMsgOuterClass.IdentityMsgOrBuilder> 
          getIdenFieldBuilder() {
        if (idenBuilder_ == null) {
          idenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.IdentityMsgOuterClass.IdentityMsg, protocol.IdentityMsgOuterClass.IdentityMsg.Builder, protocol.IdentityMsgOuterClass.IdentityMsgOrBuilder>(
                  getIden(),
                  getParentForChildren(),
                  isClean());
          iden_ = null;
        }
        return idenBuilder_;
      }

      private Object fileId_ = "";
      /**
       * <pre>
       * firmware id
       * </pre>
       *
       * <code>optional string FileId = 2 [default = ""];</code>
       */
      public boolean hasFileId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * firmware id
       * </pre>
       *
       * <code>optional string FileId = 2 [default = ""];</code>
       */
      public String getFileId() {
        Object ref = fileId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * firmware id
       * </pre>
       *
       * <code>optional string FileId = 2 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getFileIdBytes() {
        Object ref = fileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * firmware id
       * </pre>
       *
       * <code>optional string FileId = 2 [default = ""];</code>
       */
      public Builder setFileId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * firmware id
       * </pre>
       *
       * <code>optional string FileId = 2 [default = ""];</code>
       */
      public Builder clearFileId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileId_ = getDefaultInstance().getFileId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * firmware id
       * </pre>
       *
       * <code>optional string FileId = 2 [default = ""];</code>
       */
      public Builder setFileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileId_ = value;
        onChanged();
        return this;
      }

      private int begin_ ;
      /**
       * <pre>
       * 固件开始位置
       * </pre>
       *
       * <code>optional int32 Begin = 3 [default = 0];</code>
       */
      public boolean hasBegin() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * 固件开始位置
       * </pre>
       *
       * <code>optional int32 Begin = 3 [default = 0];</code>
       */
      public int getBegin() {
        return begin_;
      }
      /**
       * <pre>
       * 固件开始位置
       * </pre>
       *
       * <code>optional int32 Begin = 3 [default = 0];</code>
       */
      public Builder setBegin(int value) {
        bitField0_ |= 0x00000004;
        begin_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 固件开始位置
       * </pre>
       *
       * <code>optional int32 Begin = 3 [default = 0];</code>
       */
      public Builder clearBegin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        begin_ = 0;
        onChanged();
        return this;
      }

      private int length_ = 1400;
      /**
       * <pre>
       * 回传固件长度限制
       * </pre>
       *
       * <code>optional int32 Length = 4 [default = 1400];</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 回传固件长度限制
       * </pre>
       *
       * <code>optional int32 Length = 4 [default = 1400];</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <pre>
       * 回传固件长度限制
       * </pre>
       *
       * <code>optional int32 Length = 4 [default = 1400];</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000008;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 回传固件长度限制
       * </pre>
       *
       * <code>optional int32 Length = 4 [default = 1400];</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        length_ = 1400;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.DownloadReq)
    }

    // @@protoc_insertion_point(class_scope:protocol.DownloadReq)
    private static final DownloadReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DownloadReq();
    }

    public static DownloadReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<DownloadReq>
        PARSER = new com.google.protobuf.AbstractParser<DownloadReq>() {
      @Override
      public DownloadReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DownloadReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DownloadReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DownloadReq> getParserForType() {
      return PARSER;
    }

    @Override
    public DownloadReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DownloadRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.DownloadRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>required uint32 Code = 1;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>required uint32 Code = 1;</code>
     */
    int getCode();

    /**
     * <pre>
     * 固件总长度
     * </pre>
     *
     * <code>optional int32 Total = 2 [default = 0];</code>
     */
    boolean hasTotal();
    /**
     * <pre>
     * 固件总长度
     * </pre>
     *
     * <code>optional int32 Total = 2 [default = 0];</code>
     */
    int getTotal();

    /**
     * <pre>
     * 固件开始位置
     * </pre>
     *
     * <code>optional int32 Begin = 3 [default = 0];</code>
     */
    boolean hasBegin();
    /**
     * <pre>
     * 固件开始位置
     * </pre>
     *
     * <code>optional int32 Begin = 3 [default = 0];</code>
     */
    int getBegin();

    /**
     * <pre>
     * 回传固件的长度
     * </pre>
     *
     * <code>optional int32 Length = 4 [default = 0];</code>
     */
    boolean hasLength();
    /**
     * <pre>
     * 回传固件的长度
     * </pre>
     *
     * <code>optional int32 Length = 4 [default = 0];</code>
     */
    int getLength();

    /**
     * <pre>
     * 固件数据
     * </pre>
     *
     * <code>optional bytes Data = 5 [default = ""];</code>
     */
    boolean hasData();
    /**
     * <pre>
     * 固件数据
     * </pre>
     *
     * <code>optional bytes Data = 5 [default = ""];</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code protocol.DownloadRsp}
   */
  public  static final class DownloadRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.DownloadRsp)
      DownloadRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DownloadRsp.newBuilder() to construct.
    private DownloadRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DownloadRsp() {
      data_ = com.google.protobuf.Internal.bytesDefaultValue("");
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DownloadRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              total_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              begin_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              length_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Download.internal_static_protocol_DownloadRsp_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Download.internal_static_protocol_DownloadRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DownloadRsp.class, Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>required uint32 Code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 返回结果
     * </pre>
     *
     * <code>required uint32 Code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int TOTAL_FIELD_NUMBER = 2;
    private int total_;
    /**
     * <pre>
     * 固件总长度
     * </pre>
     *
     * <code>optional int32 Total = 2 [default = 0];</code>
     */
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 固件总长度
     * </pre>
     *
     * <code>optional int32 Total = 2 [default = 0];</code>
     */
    public int getTotal() {
      return total_;
    }

    public static final int BEGIN_FIELD_NUMBER = 3;
    private int begin_;
    /**
     * <pre>
     * 固件开始位置
     * </pre>
     *
     * <code>optional int32 Begin = 3 [default = 0];</code>
     */
    public boolean hasBegin() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 固件开始位置
     * </pre>
     *
     * <code>optional int32 Begin = 3 [default = 0];</code>
     */
    public int getBegin() {
      return begin_;
    }

    public static final int LENGTH_FIELD_NUMBER = 4;
    private int length_;
    /**
     * <pre>
     * 回传固件的长度
     * </pre>
     *
     * <code>optional int32 Length = 4 [default = 0];</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 回传固件的长度
     * </pre>
     *
     * <code>optional int32 Length = 4 [default = 0];</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * 固件数据
     * </pre>
     *
     * <code>optional bytes Data = 5 [default = ""];</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 固件数据
     * </pre>
     *
     * <code>optional bytes Data = 5 [default = ""];</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, total_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, begin_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, length_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, total_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, begin_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, length_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DownloadRsp)) {
        return super.equals(obj);
      }
      DownloadRsp other = (DownloadRsp) obj;

      if (hasCode() != other.hasCode()) return false;
      if (hasCode()) {
        if (getCode()
            != other.getCode()) return false;
      }
      if (hasTotal() != other.hasTotal()) return false;
      if (hasTotal()) {
        if (getTotal()
            != other.getTotal()) return false;
      }
      if (hasBegin() != other.hasBegin()) return false;
      if (hasBegin()) {
        if (getBegin()
            != other.getBegin()) return false;
      }
      if (hasLength() != other.hasLength()) return false;
      if (hasLength()) {
        if (getLength()
            != other.getLength()) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      if (hasTotal()) {
        hash = (37 * hash) + TOTAL_FIELD_NUMBER;
        hash = (53 * hash) + getTotal();
      }
      if (hasBegin()) {
        hash = (37 * hash) + BEGIN_FIELD_NUMBER;
        hash = (53 * hash) + getBegin();
      }
      if (hasLength()) {
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getLength();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DownloadRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DownloadRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DownloadRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DownloadRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DownloadRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DownloadRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DownloadRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DownloadRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DownloadRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DownloadRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DownloadRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DownloadRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DownloadRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.DownloadRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.DownloadRsp)
        DownloadRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Download.internal_static_protocol_DownloadRsp_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Download.internal_static_protocol_DownloadRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DownloadRsp.class, Builder.class);
      }

      // Construct using protocol.Download.DownloadRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        total_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        begin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = com.google.protobuf.Internal.bytesDefaultValue("");
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Download.internal_static_protocol_DownloadRsp_descriptor;
      }

      @Override
      public DownloadRsp getDefaultInstanceForType() {
        return DownloadRsp.getDefaultInstance();
      }

      @Override
      public DownloadRsp build() {
        DownloadRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DownloadRsp buildPartial() {
        DownloadRsp result = new DownloadRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.total_ = total_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.begin_ = begin_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.length_ = length_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DownloadRsp) {
          return mergeFrom((DownloadRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DownloadRsp other) {
        if (other == DownloadRsp.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        if (other.hasBegin()) {
          setBegin(other.getBegin());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasCode()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DownloadRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DownloadRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>required uint32 Code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>required uint32 Code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>required uint32 Code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回结果
       * </pre>
       *
       * <code>required uint32 Code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private int total_ ;
      /**
       * <pre>
       * 固件总长度
       * </pre>
       *
       * <code>optional int32 Total = 2 [default = 0];</code>
       */
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 固件总长度
       * </pre>
       *
       * <code>optional int32 Total = 2 [default = 0];</code>
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <pre>
       * 固件总长度
       * </pre>
       *
       * <code>optional int32 Total = 2 [default = 0];</code>
       */
      public Builder setTotal(int value) {
        bitField0_ |= 0x00000002;
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 固件总长度
       * </pre>
       *
       * <code>optional int32 Total = 2 [default = 0];</code>
       */
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        total_ = 0;
        onChanged();
        return this;
      }

      private int begin_ ;
      /**
       * <pre>
       * 固件开始位置
       * </pre>
       *
       * <code>optional int32 Begin = 3 [default = 0];</code>
       */
      public boolean hasBegin() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * 固件开始位置
       * </pre>
       *
       * <code>optional int32 Begin = 3 [default = 0];</code>
       */
      public int getBegin() {
        return begin_;
      }
      /**
       * <pre>
       * 固件开始位置
       * </pre>
       *
       * <code>optional int32 Begin = 3 [default = 0];</code>
       */
      public Builder setBegin(int value) {
        bitField0_ |= 0x00000004;
        begin_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 固件开始位置
       * </pre>
       *
       * <code>optional int32 Begin = 3 [default = 0];</code>
       */
      public Builder clearBegin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        begin_ = 0;
        onChanged();
        return this;
      }

      private int length_ ;
      /**
       * <pre>
       * 回传固件的长度
       * </pre>
       *
       * <code>optional int32 Length = 4 [default = 0];</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 回传固件的长度
       * </pre>
       *
       * <code>optional int32 Length = 4 [default = 0];</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <pre>
       * 回传固件的长度
       * </pre>
       *
       * <code>optional int32 Length = 4 [default = 0];</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000008;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 回传固件的长度
       * </pre>
       *
       * <code>optional int32 Length = 4 [default = 0];</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        length_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.Internal.bytesDefaultValue("");
      /**
       * <pre>
       * 固件数据
       * </pre>
       *
       * <code>optional bytes Data = 5 [default = ""];</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 固件数据
       * </pre>
       *
       * <code>optional bytes Data = 5 [default = ""];</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * 固件数据
       * </pre>
       *
       * <code>optional bytes Data = 5 [default = ""];</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 固件数据
       * </pre>
       *
       * <code>optional bytes Data = 5 [default = ""];</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.DownloadRsp)
    }

    // @@protoc_insertion_point(class_scope:protocol.DownloadRsp)
    private static final DownloadRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DownloadRsp();
    }

    public static DownloadRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<DownloadRsp>
        PARSER = new com.google.protobuf.AbstractParser<DownloadRsp>() {
      @Override
      public DownloadRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DownloadRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DownloadRsp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DownloadRsp> getParserForType() {
      return PARSER;
    }

    @Override
    public DownloadRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_DownloadReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_DownloadReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_DownloadRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_DownloadRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Download.proto\022\010protocol\032\033IdentityMsgO" +
      "uterClass.proto\"l\n\013DownloadReq\022#\n\004Iden\030\001" +
      " \002(\0132\025.protocol.IdentityMsg\022\020\n\006FileId\030\002 " +
      "\001(\t:\000\022\020\n\005Begin\030\003 \001(\005:\0010\022\024\n\006Length\030\004 \001(\005:" +
      "\0041400\"b\n\013DownloadRsp\022\014\n\004Code\030\001 \002(\r\022\020\n\005To" +
      "tal\030\002 \001(\005:\0010\022\020\n\005Begin\030\003 \001(\005:\0010\022\021\n\006Length" +
      "\030\004 \001(\005:\0010\022\016\n\004Data\030\005 \001(\014:\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.IdentityMsgOuterClass.getDescriptor(),
        }, assigner);
    internal_static_protocol_DownloadReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_DownloadReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_DownloadReq_descriptor,
        new String[] { "Iden", "FileId", "Begin", "Length", });
    internal_static_protocol_DownloadRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_DownloadRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_DownloadRsp_descriptor,
        new String[] { "Code", "Total", "Begin", "Length", "Data", });
    protocol.IdentityMsgOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
